- demos/node/.vscode/launch.json
- demos/node/crasher.js
- package.nls.json
- scripts/generate-dap-api.js
- src/adapter/sources.ts
- src/common/promiseUtil.ts
- src/common/sourceUtils.ts
- src/dap/api.d.ts
- src/dap/connection.ts
- src/dap/errors.ts
- src/debugServer.ts
- src/flatSessionLauncher.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/node/bootloader.ts
- src/targets/node/callback-file.ts
- src/targets/node/killTree.ts
- src/targets/node/nodeLauncher.ts
- src/targets/node/processLauncher.ts
- src/targets/node/program.ts
- src/targets/node/restartPolicy.ts
- src/targets/node/subprocessProgramLauncher.ts
- src/targets/node/terminalProgramLauncher.ts
- src/targets/targets.ts
- src/test/node/node-runtime.test.ts
- src/test/test.ts
- src/test/testRunner.ts
- src/ui/sessionManager.ts
This implements the `console` option, allowing programs to be opened in the
integration debug console, terminal, or external terminal. I also took the
opportunity to look at lifecycles a little more: I've adjusted the program
launchers (now a subprocess launcher and a terminal launcher) to be stateless
and create `IProgram` instances that carry the session state.
This also involves implementing the callback from the subprocess to the parent
one (containing the process ID and runtime metadata). In the debug2
implementation, we evaluate and return an expression via CDP. In here I've
implemented it as a file callback, where the process writes JSON that the
debug adapter reads. I think this might be a little more simple and reliable--
there's a pretty decent chunk of logic in debug2 about …
> feat: implement console, refactor lifecycles slightly

- src/adapter/threads.ts
Visual studio doesn't like every thread having the same id and will throw an error. 
Adding a unique monotonically increasing ID to each thread to be consistent with the protocol.
> fix: assign unique id to each thread

- scripts/generate-cdp-api.js
- src/binder.ts
- src/cdp/api.d.ts
- src/cdp/connection.ts
- src/targets/browser/browserTargets.ts
- src/targets/node/nodeAttacher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/node/nodeTarget.ts
- src/targets/targets.ts
- src/test/node/node-runtime-attaching-attaches-to-existing-processes.txt
- src/test/node/node-runtime.test.ts
- src/test/test.ts
Stacked on #47. The issue was that when we attach to a running Node process, it already has all the scripts and threads loaded in memory, and it was sending this effectively instantly--before we finished setting up our listeners on the CDP connection.
My initial approach was to move the call to `await this._cdp.Debugger.enable({});` to the `afterBind()` hook, but I realize it was probably just luck that made it work with Node launches initially, so instead I implementing a pause/resume mechanic in the CDP connection, allowing us to pause events sent down the CDP until after we're listening and ready to start receiving them.
> fix: pause CDP events until the adapter is fully connected to avoid races

- src/configuration.ts
- src/targets/sourcePathResolver.ts
Also pulling the default sourceMapPathOverrides from v1/v2
> fix: use default sourceMapOverrides if not in launch config.

- src/dap/connection.ts
- src/dap/flatSessionConnection.ts
The telemetry wasn't working for the flat session server model because the ChildConnection don't user/call the init method of DapConnections.
I added extra code to make the telemetryReporter be set for these connections too....
> Fix telemetry for server

- demos/node/child.js
- demos/node/parent.js
- package.json
- package.nls.json
- src/adapter/threads.ts
- src/common/urlUtils.ts
- src/configuration.ts
- src/targets/browser/browserTargets.ts
- src/targets/node/bootloader.ts
- src/targets/node/lease-file.ts
- src/targets/node/nodeAttacher.ts
- src/targets/node/nodeLauncher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/node/nodeTarget.ts
- src/targets/node/program.ts
- src/targets/targets.ts
- src/test/node/node-runtime-attaching-attaches-children-of-child-processes.txt
- src/test/node/node-runtime.test.ts
A similar mechanism was needed for both scenarios, so they're here. The
NodeTarget now has a lifecycle object, and for node launches we hook into
the `initialized()` point to set a breakpoint on the main script file that
the user asked us to run.
We need to be paused to evaluate code, so the NodeAttacher uses the
initialized() point to request a pause, and when the first pause happens it
retrieves telemetry from the child process, and also installs the environment
variables necessary to instrument children. After doing this, any forked
children are detected automagially--you can try this out by running
`node demos/node/parent.js --inspect` and attaching to it; you can view and
debug in the child process.
The thorny point is around uninstallation when we detach; we'll have a bunch
of …
> feat: attach to child processes of attached children, support stopOnEntry

- package.json
- package.nls.json
- src/baseConfigurationProvider.ts
- src/binder.ts
- src/cdp/connection.ts
- src/chromeDebugConfigurationProvider.ts
- src/common/logging/consoleLogSink.ts
- src/common/logging/fileLogSink.ts
- src/common/logging/index.ts
- src/common/logging/logger.ts
- src/configuration.ts
- src/dap/connection.ts
- src/extension.ts
- src/int-chrome/testSetup.ts
- src/nodeDebugConfigurationProvider.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/node/nodeTarget.ts
- src/targets/sourcePathResolver.ts
- src/telemetry/unhandledErrorReporter.ts
- src/test/common/logging.test.ts
- src/test/extension/nodeConfigurationProvidersTests.ts
This is inspired by the previous debug adapter in functionality. It
buffers written logs until we attach sinks, as we can log information
before the DAP or extension context is available. It uses the existing
`trace` option, but is now (optionally) an object with some additonal information
which allows for filtering; since we now log all DAP and CDP messages,
I figured this could be useful during development to cut down on some
noise.
```ts
export interface ILoggingConfiguration {
/**
* Configures whether logs are also returned to the debug console.
* Defaults to false.
*/
console: boolean;
/**
* Configures the level of logs recorded. Defaults to "Verbose".
*/
level: string;
/**
* Configures where on disk logs are written. If this is null, no logs
* will be written, otherwise the …
```
> feat: implement logging

- demos/web-worker/.vscode/launch.json
- package.nls.json
- src/common/logging/fileLogSink.ts
- src/common/logging/index.ts
- src/common/logging/logger.ts
- src/common/urlUtils.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/browserTargets.ts
- src/telemetry/telemetryReporter.ts
- src/test/common/urlUtils.test.ts
- src/test/testRunner.ts
- src/ui/sessionManager.ts
This Adds filtering by `url`/`urlFilter` to the browser attacher --
previously it'd always connect to the first tab/target, which is not
always desirable if the user has several tabs open.
We also now support timeouts in the browser attacher and launcher,
set the network cache setting on the target page, and send and log
telemetry about the attached page, like the previous debug adapter did.
> feat: option support in browser attach

- demos/simple-html/index.html
- src/baseConfigurationProvider.ts
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/chromeDebugConfigurationProvider.ts
- src/nodeDebugConfigurationProvider.ts
- src/targets/browser/browserLauncher.ts
This adds support for the "file" option in Chrome's launch.json to open
and HTML page. Support for this was straightforward. I also did some
work on the config providers to make HTML pages F5-able without needing
a preexisting launch configuration.
There's an outstanding issue where breakpoints set before Chrome is launch are _sent_ to Chrome, but don't seem to apply. Pinged Dmitry for ideas on this, seems like some kind of race. https://github.com/microsoft/vscode-pwa/issues/79
> feat: support opening an HTML page

- src/telemetry/telemetryReporter.ts
Telemetry properties were being ignored because we shouldn't convert data into a string
> Fix telemetry properties

- src/binder.ts
- src/build/strings.ts
- src/cdp/transport.ts
- src/common/cancellation.ts
- src/common/logging/index.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/launcher.ts
- src/targets/node/extensionHostAttacher.ts
- src/targets/node/nodeAttacher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/node/watchdog.ts
- src/targets/targets.ts
- src/test/common/cancellation.test.ts
Copied the VS Code CancellationTokenSource implementation into here,
since when running in a bespoke debug server (e.g. VS proper) we don't
have access to vscode's concrete types.
Then bubbled it through the launchers and secondary methods. Previously
for instance you could get stuck if you tried to remote attach to a
server that discarded traffic on a port, common in Azure VMs.
Now we show a timeout correctly.
Also fixes some minor error message handling bugs. (Fixes #74)
Timeout options for parity (https://github.com/microsoft/vscode-pwa/issues/26)
> feat: better timeouts, cancellation tokens

- gulpfile.js
- src/binder.ts
- src/common/logging/fileLogSink.ts
- src/common/logging/logger.ts
- src/configuration.ts
- src/dap/custom.d.ts
- src/targets/node/extensionHostAttacher.ts
- src/targets/node/extensionHostLauncher.ts
- src/targets/node/killTree.ts
- src/targets/node/nodeAttacher.ts
- src/targets/node/nodeAttacherBase.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/targets.ts
Just something we weren't doing. The existing adapter reads the process
ID when it attaches to a target, and so did we (for Node targets). I
shifted around some logic into a `NodeAttacherBase` so that we can
reuse that query in the extension host, and then from there we reuse
the `TerminalProgram` to track the liveness of the vscode instance
by process ID.
Things I tested that work (from a vscode 'parent' debugging a 'child'):
- Halting debugging from inside the parent instance kills the child
- Closing the child clears the debugging state in the parent (I think
it's actually a minor bug in the existing debug adapters where
this doesn't happen...)
- Restarting works as expected
Finishes/Fixes https://github.com/microsoft/vscode-pwa/issues/58
> feat: track vscode lifecycles correctly

- src/cdp/transport.ts
- src/common/cancellation.ts
- src/common/findOpenPort.ts
- src/configuration.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/launcher.ts
- src/test/common/cancellation.test.ts
We use the Chrome debugger to debug VS Code itself. Launching this
depended on some specific behaviors  we didn't have before:
- the URL is optional by default, only navigate
the page if a URL is provided
- don't set the user data dir unless explicitly requested when a
custom runtime executable is provided
- when a port is provided, skip scanning the browser stdout and instead
just poll for the debugger on that port (vscode's launch script
didn't display the magic string the launcher was after)
- some cleanup as I was debugging in the chrome launcher; allow
providing the `--remote-debugging-port` to be equivalent to an
explicit `port` option.
> feat: chrome behavior parity, allow debugging vscode

- package.json
- src/test/logger.ts
- src/test/testIntegrationUtils.ts
This solves part of the telemetry events not being matched in the expected text for some tests.
I have a lot of unit test failures when I run the tests, so it's difficult to see whether this addresses all the telemetry issues in the tests or not.
I added a .only option to itIntegrates
> Ignore telemetry events in tests

- package-lock.json
- package.json
- src/binder.ts
- src/build/generate-contributions.ts
- src/configuration.ts
- src/ui/processPicker.ts
It won't be invoked when old node-debug dispatches to pwa-node, or for the VS case
- And always activate when node-debug activates
- And add "request" back for tests
> Apply defaults to config inside adapter, without the config provider involved

- src/test/evaluate/evaluate.ts
- src/test/test.ts
The telemetry changes broke the await p.dap.once('output') logic because it returned for the telemetry event instead of the output event. Filtering out the telemetry events in once fixes that issue
> Ignore telemetry events when we await a once output message

- demos/webpack/.vscode/launch.json
- demos/webpack/package-lock.json
- demos/webpack/src/consume-lib.js
- demos/webpack/src/lib.ts
- demos/webpack/webpack.lib.js
- src/build/generate-contributions.ts
- src/configuration.ts
- src/targets/browser/browserPathResolver.ts
- src/targets/node/nodeSourcePathResolver.ts
- src/targets/sourceMapOverrides.ts
- src/targets/sourcePathResolver.ts
- src/test/common/sourceMapOverrides.test.ts
This involved adding a 'non-capturing group' syntax for the host map
overrides section. I used the RegEx-style `?:*` sequence, which is not
that pretty, I'm open to ideas. Anyway, this works. The default
source map URIs in webpack are actually formed[1] like:
```
webpack://[namespace]/[resourcePath]
```
It just happens the namespace is usually empty for main targets, but
this is configurable is defaults to `lib` for library targets,
hence #60. This PR adds a non-capturing group for the namespace.
Also makes source map overrides its own class, which saves processing
time (we can pre-parse and generate the regexes) and makes it more
readily testable.
1. https://github.com/webpack/webpack/blob/91a9f97657b34375cd99e8ba8ef13dd795f1e7c3/lib/SourceMapDevToolPlugin.js#L115
> feat: support webpack namespaces in source map overrides

- src/adapter/breakpoints.ts
- src/adapter/debugAdapter.ts
- src/binder.ts
- src/common/promiseUtil.ts
Unless I'm misunderstanding something, I thing this is the right fix for #79. Now we will wait on the configurationDone event, and wait to finish setting the breakpoints that came at startup before configurationDone, before calling `runIfWaitingForDebugger`.
> Fix race condition in startup

- src/binder.ts
- src/configuration.ts
when debugging with the nightly extension.
Otherwise it is not necessarily obvious which extension is being used.
> Show a message in the debug console

- src/adapter/stackTrace.ts
- src/test/stacks/stacks-anonymous-scopes.txt
- src/test/stacks/stacks-async-disables.txt
- src/test/stacks/stacks-async.txt
- src/test/stacks/stacks-blackboxed.txt
- src/test/stacks/stacks-return-value.txt
- src/test/stacks/stacks-source-map.txt
- src/test/stacks/stacks-stack-in-eval.txt
- src/test/variables/variables-setvariable-scope.txt
Fixes https://github.com/microsoft/vscode-pwa/issues/150
- We always used the scope name as the reported name to VS Code,
but there might be multiple scope names of different types.
- Also in the issue, I noticed that `this` wasn't present. In the old
adapters, we always add `this` to the top call scope. In PWA that
was only happening if the top scope was `local` (and we never tried
to add it anywhere if that wasn't the case). The most technically
correct thing to do would be to show it at the nearest `local` scope,
but I think showing it at the top is more useful and is what
people are used to.
> fix: call frame names appearing duplicated, `this` not appearing

- src/baseConfigurationProvider.ts
- src/targets/sourceMapOverrides.ts
- src/test/common/sourceMapOverrides.test.ts
- The previous adapter manually replaces[1] webRoot in the source map
overrides. Do the same here for parity.
- The `source-map` module normalizes URLs before they're given back to
us, but the previous adapter didn't do this. Overrides that target
prefixes like "webpack:///./*" don't work, because the extraneous
"./" gets removed.
1. https://github.com/microsoft/vscode-chrome-debug/blob/075b94d825294b5aa7992fee55125982ee44a669/src/chromeDebugAdapter.ts#L566
Fixes https://github.com/microsoft/vscode-pwa/issues/147
And most likely https://github.com/microsoft/vscode-pwa/issues/140
> fix: source map override handling issues

- demos/web-worker/index.html
- gulpfile.js
- package-lock.json
- package.json
- src/common/urlUtils.ts
- src/targets/browser/browserPathResolver.ts
- src/test/breakpoints/breakpoints-configure-query-params.txt
- src/test/breakpoints/breakpointsTest.ts
- testWorkspace/web/script-with-query-param.html
- 'eat' query parameters in the url pattern we send with breakpoints
- remove params when creating absolute paths so that all mapping back
and forth works.
- add a test case :)
Fixes #166
> fix: ignore query parameters on parsed scripts

- src/adapter/breakpoints.ts
- src/adapter/debugAdapter.ts
- src/adapter/threads.ts
- src/common/promiseUtil.ts
- src/statistics/breakpointsStatistics.ts
- src/test/breakpoints/breakpoints-launched-source-map-set-compiled-2.txt
- src/test/breakpoints/breakpoints-launched-source-map-set-compiled.txt
- src/test/breakpoints/breakpointsTest.ts
This is a followup to #169 and the discussion in #162. We now store
a deferred 'set complete' on the breakpoint, which we resolve in a
after returning the set response over DAP. We then guard updates around
this promise and skip sending them if we haven't sent the initial
`setBreakpoints` response yet (the response will contain their full
state with any updates that came in).
Also, if we see that we pause on a breakpoint that we haven't sent
back yet, we'll wait a moment for it to try to be set. I don't _think_
this will ever be hit in VS Code, since it sends all breakpoint
updates individually after the initial configuration, but it's there
regardless and seems to work well.
> fix: ensure bp set completes before updates or pauses

- src/adapter/variables.ts
- src/test/breakpoints/breakpointsTest.ts
- src/test/logger.ts
- src/test/variables/variables-setvariable-evaluatename.txt
- src/test/variables/variablesTest.ts
Wasn't implemented before. Fixes #183. Nothing too crazy, we already had
an "object.wrap" function that created a RemoteObject that used the
parent's DAP, now we actually bubble accessor information through
there as well.
> feat: set evaluateName on vars, allowing for copying

- src/adapter/breakpointPredictor.ts
- src/adapter/debugAdapter.ts
- src/adapter/sourceMapCache.ts
- src/adapter/sources.ts
The old debug adapter took about ~100ms to set a breakpoint. The new one
was taking ~300ms. It turns out the first time you try to resolve a
breakpoint location with a parsed sourcemap, it takes roughly ~200ms,
and roughly ~0ms after that point. We weren't caching sourcemaps,
reparsing them every time we set a breakpoint. The math adds up :)
Fixes #178
> fix: cache source maps to speed up setting

- src/adapter/completions.ts
- src/adapter/templates/enumerateProperties.ts
- src/adapter/templates/getArrayProperties.ts
- src/adapter/templates/getArraySlots.ts
- src/adapter/templates/index.ts
- src/adapter/templates/previewThis.ts
- src/adapter/templates/toStringForClipboard.ts
- src/adapter/threads.ts
- src/adapter/variables.ts
- src/test/completion/completion.test.ts
Completion previously was pretty basic. This does more work to get it
better data and correct type...
1. I made a "template function" helper. It's very scary, but in the
debug adapter we heavily rely on sending non-trivial chunks of JS
over to the adapter, and being able to write these in TypeScript with
all the associated checking and linter is, in my opinion, preferable.
2. Did some work on the property walker (template) function to have it
try to infer class types, properties, etc. correctly. Previously it
only ever emitted `property` and `function`.
3. Better detection and handling of element kinds, particularly handling
arrays correctly, which we didn't really do before.
4. Allow referencing locals declared elsewhere in the REPL expression,
useful for writing more complex statements. …
> feat: revamp completion

- README.md
- src/targets/node/subprocessProgramLauncher.ts
Closes https://github.com/microsoft/vscode-js-debug/issues/201
I also noticed `gulp build --nightly` does not seem to be a task; `gulp package` worked for me.
> fix: allow omitting "program" from launch.json

- .ci/common-validation.yml
- src/adapter/breakpoints.ts
- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/breakpoints/entryBreakpoint.ts
- src/adapter/breakpoints/hitCondition.ts
- src/adapter/breakpoints/userDefinedBreakpoint.ts
- src/adapter/threads.ts
- src/dap/errors.ts
- src/targets/node/nodeTarget.ts
- src/test/breakpoints/breakpoints-first-line-breaks-if-requested.txt
- src/test/breakpoints/breakpoints-first-line-does-not-break-if-not-requested.txt
- src/test/breakpoints/breakpoints-hot-transpiled-adjusts-breakpoints.txt
- src/test/breakpoints/breakpoints-hot-transpiled-breaks-on-first-line.txt
- src/test/breakpoints/breakpoints-hot-transpiled-does-not-adjust-already-correct.txt
- src/test/breakpoints/breakpointsTest.ts
- src/test/node/node-runtime-attaching-attaches-children-of-child-processes.txt
- src/test/node/node-runtime-attaching-attaches-to-existing-processes.txt
- src/test/node/node-runtime-attaching-retries-attachment.txt
- src/test/testRunner.ts
- testWorkspace/simpleNode/index.js
- testWorkspace/tsNode/double.ts
- testWorkspace/tsNode/index.js
> **Note:** this is stacked on #174. That PR should be fast-forwards-merged first, and then this should be changed to point at master.
First of all, apologies for the churn. While this change is relatively
simple, I realized that hit condition breakpoints further diverges the
user-defined breakpoints and the managed 'entrypoint' breakpoints (as
of #174), where we don't have hit conditions or DAP representations.
Therefore, there's now a base "Breakpoint" class which implements the
purely CDP-side of things, which a `UserDefinedBreakpoint` extends with
metadata around DAP, and the `EntryBreakpoint` extends in a minimal way.
After doing the split there was almost no changes the existing code
around the breakpoints, which is good evidence that we are indeed
dealing with two different types …
> feat: initial implementation of hit condition breakpoints

- src/build/generate-contributions.ts
- src/configuration.ts
- src/targets/node/nodeLauncher.ts
- src/targets/node/terminalProgramLauncher.ts
- src/test/node/node-runtime-stoponentry-launches-and-infers-entry-from-args.txt
- src/test/node/node-runtime-stoponentry-sets-an-explicit-stop-on-entry-point.txt
- src/test/node/node-runtime-stoponentry-stops-with-a-program-provided.txt
- src/test/node/node-runtime.test.ts
Fixes #201
As referenced in the comment, this isn't the ideal approach because it
was stolen from us by having a bootloader script. It should work for
most people, though, and I also allowed people to set a custom file path
in "stopOnEntry" in case the heuristics don't work (for instance, if
they start a Node program through a shell script where the path is not
present on the command line).
> fix: stopOnEntry not working with omitted program

- src/adapter/breakpointPredictor.ts
- src/adapter/sources.ts
- src/adapter/threads.ts
- src/binder.ts
- src/common/fsUtils.ts
- src/common/sourcePathResolver.ts
- src/configuration.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/browserPathResolver.ts
- src/targets/node/nodeSourcePathResolver.ts
- src/targets/sourcePathResolver.ts
- src/targets/targets.ts
- src/test/browser/browserPathResolverTest.ts
- src/test/node/node-source-path-resolver.test.ts
- src/test/testRunner.ts
Due to some limitations we can't always figure out the right webRoot in VS for Angular projects. This fix worksaround that fact by trying both <webRoot> and <webRoot>/../ClientApp at the same time.
(This fix was ported from v1: https://github.com/microsoft/vscode-chrome-debug-core/blob/87d2c194179033e38d68308027c1d1dbbc43c454/src/sourceMaps/sourceMapUtils.ts#L118 )
> Fix angular in VS

- src/targets/browser/browserPathResolver.ts
- src/test/breakpoints/breakpoints-configure-absolute-paths-in-source-maps.txt
- src/test/breakpoints/breakpointsTest.ts
We previously allowed source map file URIs, but not full absolute paths. It appears that create-react-app on Windows specifically creates sourcemaps containing absolute paths (with forward slashes instead of back slashes). This PR adds handling and a test case for those.
Fixes https://github.com/microsoft/vscode-js-debug/issues/215
> fix: absolute path handling in source map

- package-lock.json
- package.json
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/common/contributionUtils.ts
- src/extension.ts
- src/targets/node/nodeTarget.ts
- src/telemetry/opsReportBatch.ts
- src/ui/debugNpmScript.ts
- src/ui/debugScriptUI.ts
- src/ui/longPredictionUI.ts
- src/ui/npmScriptLens.ts
Fixes #196. Adds a code lens to debug an npm script. This adapter
currently doesn't support `nodebug` very well, and there are changes
coming to the terminal in #199, so I didn't implement a "Run" action
yet, but that should be straightforward once those are resolved.
By default the code lens appears atop the "script" section of the
package.json from where it opens a quick-pick, but it can also be
shown above individual scripts or hidden.
This also includes a slight modification to the contrib generator for
configuration to add some type safety.
> feat: add code lens for npm scripts

- src/adapter/threads.ts
> Send the thread 'exited' event after all other events

- src/adapter/messageFormat.ts
- src/adapter/threads.ts
- src/test/console/console-api-format-format-string.txt
- src/test/console/console-format-popular-types.txt
so that the client doesn't have to send a variables
request for every output. We will just use a variablesReference
when an object is logged, or when not all logged data gets
into the text representation
Fix #227
> Send console output as plain text when possible

- demos/babel/.vscode/launch.json
- demos/babel/main.js
- demos/babel/package-lock.json
- demos/babel/package.json
- demos/babel/test.ts
- src/adapter/breakpoints.ts
- src/adapter/sources.ts
- src/adapter/threads.ts
- src/test/breakpoints/breakpoints-hot-transpiled-user-defined-bp-on-first-line.txt
- src/test/breakpoints/breakpointsTest.ts
- testWorkspace/tsNode/index.js
- testWorkspace/tsNode/log.ts
Previously, if you had code
```
1: function add() {
2:   return 2 + 2;
3: }
```
and set a breakpoint on line 2, but the compiled code was:
```
1: // some
2: // random stuff
3: function add() {
```
Then in our entrypoint pause, we'd be notified that we hit both our
entrypoint breakpoint as well as the user breakpoint. Even though we
then adjust the user breakpoint, we were still seeing that and deciding
to stay paused incorrectly.
This adjusts the logic so that we run the pause check after handling
source maps and adjusting breakpoints.
> fix: bps that resolve at entry in hot code by url causing pauses

- src/adapter/objectPreview.ts
- src/adapter/templates/invokeGetter.ts
- src/adapter/threads.ts
- src/adapter/variables.ts
- src/test/console/console-format-popular-types.txt
- src/test/evaluate/evaluate-default.txt
- src/test/evaluate/evaluate.ts
We were being a little aggressive about declaring types 'primitive',
which prevented people from being able to view arraybuffers, for
instance. The Chrome devtools, only declarees `null`, `regexp`, and
`error` as the types without a preview, this follows that more closely.
While testing cases I also noticed that we weren't able to expand
getters like the chrome devtools can, this fixes that as well.
Later on I want to do a little cleanup around object previews, the
decoupling between the DAP, CDP, and internal representations make this
a little awkward: we lose information when we convert to the internal
`RemoteObject` type--I added a flag for getters here but I think making
things a bit tighter there could clean up some logic.
Fixes #234
> feat: improve object preview cases

- src/binder.ts
- src/targets/browser/browserLauncher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/node/program.ts
Also reworks the terminal process launcher to verify the process is
killed before returning.
Probably fixes #165
> fix: wait for targets before returning from disconnect

- src/adapter/breakpoints.ts
- src/adapter/debugAdapter.ts
- src/binder.ts
- src/cdp/connection.ts
- src/cdp/transport.ts
- src/dap/connection.ts
- src/dap/flatSessionConnection.ts
- src/debugServer.ts
- src/flatSessionLauncher.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/browserTargets.ts
- src/targets/browser/launcher.ts
- src/targets/node/nodeAttacherBase.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/targets.ts
- src/telemetry/classification.ts
- src/telemetry/opsReportBatch.ts
- src/telemetry/telemetryReporter.ts
- src/telemetry/unhandledErrorReporter.ts
- src/test/test.ts
- src/ui/debugTerminalUI.ts
- src/ui/sessionManager.ts
This uses our GDPR tooling to tag events via TypeScript annotations.
src/telemetry/classification had the telemetery event data types and
classifications, and they're exposed in the logger. I had to rework
some of our data types because, for example with the batch reports, our
tooling doesn't do arbitrary `[key: string]`'s in objects.
> feat: tag events correctly for gdpr

- src/adapter/breakpoints/logPoint.ts
- src/adapter/breakpoints/userDefinedBreakpoint.ts
- src/common/logging/logger.ts
- src/common/sourceUtils.ts
- src/dap/connection.ts
- src/dap/errors.ts
- src/test/breakpoints/breakpoints-logpoints-basic.txt
- src/test/breakpoints/breakpointsTest.ts
- src/test/sources/sourceUtils.test.ts
Fixes #226. As suggested in the original issue, we use the TS parser
to parse the code inside the {} 'blocks', which lets us handle more
complex expressions. We also now support multiple statements, and
(try to) return the last one, and log the stacks of any thrown errors
rather than silently failing. Finally, we return a verbose error to the
user in the event that their logpoint isn't valid JS, though there's
an issue with VS Code right now: https://github.com/microsoft/vscode/issues/89059
> feat: make logpoint parsing more resilient

- src/build/generate-contributions.ts
- src/build/strings.ts
- src/configuration.ts
- src/targets/node/nodeAttacher.ts
- src/targets/node/nodeLauncher.ts
- src/targets/node/restartPolicy.ts
- src/test/node/node-runtime-attaching-restarts-if-requested.txt
- src/test/node/node-runtime.test.ts
- src/test/test.ts
This borrows some code from the Node process launcher to implement
restarting process attachment. We'll print reconnecting messages to the
console while we're working on reconnection, and query the original
address/port to get a new inspector URL.
Fixes #245
> feat: allow restarting process attachment

- package.json
- src/adapter/debugAdapter.ts
- src/adapter/scriptSkipper.ts
- src/adapter/sources.ts
- src/adapter/threads.ts
- src/binder.ts
- src/common/datastructure/mapUsingProjection.ts
- src/common/sourceUtils.ts
- src/common/urlUtils.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/browserTargets.ts
- src/targets/node/nodeTarget.ts
- src/targets/targets.ts
- src/test/test.ts
Fixes #253
The basic idea is that I keep track of authored source skip status separately from generated scripts', and instead of sending their paths to the runtime, send the ranges in the file that is skipped.
Since we have to send this separately per scriptID to each Cdp, it got a lot easier to change ScriptSkipper from one shared instance per root session, to one instance per Target. To get the instances to share toggle statuses under the same root session, they now fire events at each other with their root target id whenever a toggle happens.
Also some other minor tweaks and fixes.
> Handle skipFiles for multiple source files built into a bundle

- src/adapter/sources.ts
- src/adapter/threads.ts
- src/binder.ts
I was focused on Node before, Chrome is different. In Node, the target
disconnecting is generally 1:1 with the program termination. But in
Chrome, the target (tab) closes before the browser does, and there are
a few more events that get sent out.
Additionally, when tearing down DAP we were previously verbosely
signalling that all sources were removed. This happened during the
disposal process, after everything else was torn down, and they weren't
necessary. Remove them.
> fix: disconnected event ordering, again

- src/cdp/transport.ts
`WebSocketTransport.onmessage` does not match the `ITransport` interface, it is missing the `receivedTime: bigint`. Unfortunately TypeScript is allowing this and I am not sure why.
The missing parameter caused a runtime error when the registered `onmessage` handler assumed it could use `receivedTime` but it was actually undefined. 
fixes #258
> fix: missing receivedTime param on WebSocketTransport type

- package.json
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/common/contributionUtils.ts
- src/configuration.ts
- src/extension.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/browserTargets.ts
* Minimum changed needed to support `msedge` debugger type, it is just an alias for `chrome`.
* This change is equivalent to the launch.json `{type: 'chrome', runTimeExecutable: 'path/to/msedge.exe'}`.
* Minimum change needed to support backwards compatibility with WebView2 launch
debugging configurations (`useWebView`) from [vscode-edge-debug2][1].
Follow-ups to consider:
* Separate `chrome` and `msedge` debugger type configurations with Edge strings.
* Validate `useWebView` configuration is configured with `runTimeExecutable`.
* Tests for `useWebView` configuration.
* Add browser `version` support (`stable`, `beta`, `dev`, `canary`) for Microsoft Edge (Chromium)
to match backwards compatibility with [vscode-edge-debug2][1].
* Deprecate `{useWebView: 'advanced'}` in favor of …
> feat: WebView2 debugging support

- src/adapter/threads.ts
Fix #279
Need to force a newline here, because VS Code gives the DA control over whether logs should end with a newline.
> Add newline to simple text output event

- src/common/urlUtils.ts
Users configuring `file` will not get their target filtered after launch.
Add `file` property to filter check created for configs.
Users may provide a file instead of url, in that case the file path will be converted into a file url (`file://`) and loaded after launch.
The `'file' in config` was needed for TypeScript because `attach` configurations do not have `file` property by default.
Removed restrictive CDP type from filter, this will be helpful for an upcoming web view change.
> fix: filter should match against `file` property

- gulpfile.js
- package-lock.json
- package.json
- src/common/hash/hash.ts
The hash speed was bugging me, particularly since we're soon going to
need to hash some files twice (as of #277) so last night I wanted to see if a
webassembly version would fare better. Turns out it does. Hashing 1KB:
```
7,520 ops/sec > current (1x)
72,500 ops/sec > wasm (9.64x)
Benches: 2
Fastest: wasm
Elapsed: 10.9s
```
The current JS algorithm only is hasing 7.5MB/s, which may sound like
a decent amount, but remember some node_modules can be massive. This
brings up a bit.
> feat: use wasm content hash implementation

- src/targets/browser/browserLauncher.ts
- src/targets/browser/browserTargets.ts
- src/targets/browser/launcher.ts
- src/targets/targets.ts
In a [previous change][1] I introduced basic debugging support for WebView2 targets, that change lacked support for web views that were created under multiple browser processes because the web views would start under ports not known by our debugger.
In this change we add support for multiple browser processes by leveraging the web view environment variable: `WEBVIEW2_PIPE_FOR_SCRIPT_DEBUGGER ` which allows us to listen on a known pipe hosted by the OS for any web view process communication, the specific details can be [read here][2].
1. Start listening to the pipe before the web view process is launched.
2. Wait to attach until after the matching target sends its port over the pipe.
3. Keep listening on the pipe for any web views to resume because all web views created under our debugger …
> feat: support multi-browser process web view debugging

- src/test/node/process-tree.test.ts
- src/ui/processPicker.ts
- src/ui/processTree/baseProcessTree.ts
- src/ui/processTree/darwinProcessTree.ts
- src/ui/processTree/processTree.ts
- src/ui/processTree/windowsProcessTree.ts
Previously if you attached to a process in a multi-root workspace, we'd
fail because we needed a working directory. This adds functionality
(which only works on *nix, unfortunately) that automatically tries to
assign the workspace folder from the working directory of the process.
Also cleans up handling of process IDs a little bit; these can be made
simpler now that we no longer need to support
the legacy debugger protocol.
> feat: assign workspace folders for attaching to processes

- src/common/urlUtils.ts
- src/test/common/urlUtils.test.ts
One more super annoying thing. _Apparently_ the debugger in electron doesn't url encode spaces in paths. This was causing the setup on my windows VM to never hit breakpoints, since it was looking for a path with %20 in it.
It looks like the old debugger didn't escape spaces at all. Maybe we should unescape everything/apply this same treatment to all characters. I don't want to modify URLs throughout the adapter to be unescaped, but this function could handle that for the purposes of matcing. Thoughts @roblourens?
> fix: spaces in paths breaking electron apps

- src/build/generate-contributions.ts
- src/build/strings.ts
- src/configuration.ts
This update reflects that the code paths of `useWebView: 'true'` and `useWebView: 'advanced'`  have merged in #285 and now both support the `urlFilter` property and honor the `timeout` property.
> fix: removed redundant useWebView: 'advanced' configuration

- gulpfile.js
VS was broken because it wasn't including hash.js in the bundled build. Side node, it might be nice to have some fail-fast way of knowing that the hashing subprocess is broken, as it's hard to diagnose at the moment (no error messages, things like stackTrace requests just start hanging because the absoluteFilePath promise never returns).
> fix: Move common js entrypoints to a single spot in the gulpfile.

- src/adapter/breakpoints.ts
- src/adapter/breakpoints/hitCondition.ts
- src/adapter/breakpoints/neverResolvedBreakpoint.ts
- src/adapter/breakpoints/userDefinedBreakpoint.ts
- src/test/breakpoints/breakpoints-hit-count-can-change-breakpoint-after-being-set.txt
- src/test/breakpoints/breakpoints-hit-count-does-not-validate-or-hit-invalid-breakpoint.txt
- src/test/breakpoints/breakpoints-hit-count-works-for-valid.txt
- src/test/breakpoints/breakpointsTest.ts
See: https://github.com/microsoft/vscode-js-debug/issues/300#issuecomment-582654597
This simply uses a new subtype "never resolved breakpoint" which has
an always-false hit condition and overrides the resolved location to
always return undefined. We use that to keep the invalid hit count
breakpoints around. Perhaps not the most efficient way since the
breakpoint still exists in the debugee, but definitely the simplest way
that doesn't involve a ton of refactoring and special casing.
Also, noticed I never wrote unit test for hit count breakpoints, so I
added some of those.
> fix: weirdness around invalid hit count breakpoints

- src/cdp/transport.ts
- src/configuration.ts
- src/targets/browser/browserLauncher.ts
- src/targets/browser/constructInspectorWSUri.ts
- src/targets/browser/launcher.ts
Add support for custom inspect uri format for Blazor
See https://github.com/microsoft/vscode-js-debug/issues/302 for more details
Added some extra logging that I used while debugging this feature
cc @connor4312 @SteveSandersonMS @roblourens
> Add support for custom inspect uri format for Blazor

- src/adapter/debugAdapter.ts
- src/adapter/threads.ts
- src/telemetry/telemetryReporter.ts
@connor4312 you are more familiar with the startup than I am, but basically the `acquireDap` call is resolved as soon as the client tries to attach, then there is no guarantee that we will wait for 'initialize' before the Thread sends its started event. This is an easy fix to delay that until 'initialize' happens, but you might have a better idea?
Fix #281
> Delay the thread started event until we get the 'initialized' request from vscode

- demos/webview/.gitignore
- demos/webview/.vscode/launch.json
- demos/webview/README.md
- demos/webview/WebView2Sample.sln
- demos/webview/WebView2Sample/HelloWebView.cpp
- demos/webview/WebView2Sample/WebView2Sample.vcxproj
- demos/webview/WebView2Sample/WebView2Sample.vcxproj.filters
- demos/webview/WebView2Sample/packages.config
- demos/webview/index.html
- demos/webview/index.js
This change adds a demo project for WebViews and provides an example `.vscode/launch.json` for debugging an application built using [Microsoft's WebView2 (developer preview)][1].
The webview demo project uses the ['Getting Started' WebView2 sample][2] provided by Microsoft as a base and fills in [the steps required to create and launch a WebView][3] against the `about:blank` page.
The demo project was test locally on Win10 x64 with Visual Studio 2019.
To run the demo:
1. Build `WebView2Sample.sln` in a x64 Debug configuration using Visual Studio.
2. Open the `demo\webview` folder in VS Code.
3. Run and Debug -> Launch WebView.
The demo project will debug `demo\webview\index.js`.
[1]: https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2
[2]: …
> add webview (developer preview) demo

- src/common/logging/fileLogSink.ts
When using the flatSessionConnection with verbose logging enabled
an error would occur when Message.__receivedTime, which is a bigint,
was logged.
```
TypeError: Do not know how to serialize a BigInt
at JSON.stringify (<anonymous>)
at FileLogSink.write (fileLogSink.js:52:36)
at Logger.log (logger.js:139:18)
at logger.js:185:48
at Array.forEach (<anonymous>)
at Logger.setup (logger.js:185:30)
at processTicksAndRejections (internaltask_queues.js:94:5
```
Example message:
```
{
tag: 'dap.receive',
timestamp: 1581435305862,
message: undefined,
metadata: {
connectionId: 0,
message: {
type: 'request',
command: 'initialize',
arguments: [Object],
seq: 1,
__receivedTime: 23614425135986n
}
},
level: 0
}
```
> fix: TypeError serializing BigInt

- src/adapter/breakpointPredictor.ts
- src/adapter/sources.ts
- src/common/pathUtils.ts
- src/targets/node/nodeSourcePathResolver.ts
- src/test/breakpoints/breakpoints-hit-count-can-change-after-set.txt
- src/test/breakpoints/breakpoints-hit-count-can-change-breakpoint-after-being-set.txt
- src/test/breakpoints/breakpoints-hit-count-works-for-valid.txt
- src/test/breakpoints/breakpoints-launched-source-map-set-compiled-2.txt
- src/test/breakpoints/breakpoints-launched-source-map-set-compiled.txt
- src/test/goldenText.ts
- src/test/node/node-source-path-resolver.test.ts
- src/test/sources/sources-allows-module-wrapper-in-node-code.txt
- src/test/sources/sources-basic-source-map.txt
- src/test/sources/sources-basic-sources.txt
- src/test/sources/sources-updated-content.txt
- src/test/sources/sources-url-and-hash.txt
Previously we didn't prefix node_internals in the DAP source, and we
also only included the basename in the source `name`, which led to
pretty ugly file trees. Now, the name will be the relative path from
the rootPath, keeping the `<eval>` or `<node_internals>` name if present.
Fixes #329
> fix: keep <node_internals> and path data in module names

- src/adapter/messageFormat.ts
- src/adapter/objectPreview/betterTypes.ts
- src/adapter/objectPreview/contexts.ts
- src/adapter/objectPreview/index.ts
- src/adapter/threads.ts
- src/test/goldenText.ts
- src/test/stacks/stacks-source-map.txt
Previously we had a lot of linting errors in the object preview code for
null assertions, since we relied on generic types return from CDP where
most properties were optional. In this PR we write some better
interfaces for various types of objects in order to elimiate these
assertions and have more durable code.
I only found one bug while doing there, where we weren't handling
certain function previews correctly :)
Fixes #319, reduces some debt.
> refactor: stronger types in obj preview, fix unescaped lines

- src/configuration.ts
- src/test/test.ts
- src/test/webview/webview.breakpoints.test.win.ts
With this change the launch test helpers will now accept an `EdgeLaunchConfiguration`.
This cleans up a TODO introduced in #325.
Note: 
The property `skipNavigateForTest` was being allowed in `ChromiumLaunchConfiguration` even when it was not defined on the interface, because `AnyLaunchConfiguration` is a union type it must now be explicitly put on the base `ChromiumLaunchConfiguration` type.
> support edge launch config types in tests

- src/adapter/completions.ts
- src/adapter/templates/enumerateProperties.ts
- src/adapter/templates/index.ts
- src/test/completion/completion.test.ts
Previously, we were making sure an expression didn't have side effects,
then sending the whole thing over an evaluating it. But the side effect
check was super aggressive, and we wanted to losen it. Chrome can
actually check expressions for side effects, so it would be cool if it
could do it for us. The property enumeration process has potential
side effects, though, so we need to split it out.
In this change, we now first evaluate the expression, with the
`throwOnSideEffect` flag if we think it might have side effects. If it
returns an object reference, then we invoke the enumeration function on
that. If it doesn't, the expression is probably a primitive type, so
enumerate on the expression directory.
Fixes #251
> feat: improve completions for debug console objects

- src/common/urlUtils.ts
Code was setting `rejectUnauthorized` to true when we were on loopback, and false when we were not (which is the opposite of what we want)
> fix: certificate validation for loopback

- src/targets/browser/browserPathResolver.ts
We were checking if the url started with "webpack:///", which would always be false. Now checking the fullSourceEntry instead (the source entry from the source map, which would have the webpack url)
> fix: angular breakpoints not hitting in VS

- src/dap/connection.ts
- src/flatSessionLauncher.ts
- src/sessionManager.ts
Debugged process names were blank in Visual Studio. Added fixes to make sure we send the initial target name, and subsequent name updates.
> fix process names in vs

- scripts/generate-dap-api.js
- src/adapter/stackTrace.ts
- src/dap/api.d.ts
This change adds code to respect the format arguments sent on a stackFrames request from DAP.
> Fix call stack formatting in Visual Studio

- src/binder.ts
On VS when we close the Node.js application instead of stopping debugging in the debugger, the connection gets hanged because the disconnect request never returns.
This happens because the launcher.onTerminated gets called twice from different places and this._terminationCount ends up valuing -1
> Quick fix for disconnect hanged issue

- package-lock.json
- package.json
- src/cdp/transport.ts
This makes it possible for the Blazor debugging middleware to redirect the connection to an external process
... which in turn is necessary to avoid blocking the debug proxy while breakpoints are being hit
... which in turn is necessary for things like the "locals" window to be able to obtain values.
> When making websocket connection, enable "follow redirects"

- package-lock.json
- package.json
- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/sources.ts
- src/common/logging/fileLogSink.ts
- src/common/sourceMaps/sourceMapFactory.ts
- src/common/sourcePathResolver.ts
- src/common/urlUtils.ts
- src/targets/node/nodeSourcePathResolver.ts
- src/targets/sourcePathResolver.ts
- src/test/breakpoints/breakpoints-hot-transpiled-works-in-remote-workspaces.txt
- src/test/breakpoints/breakpointsTest.ts
- src/test/test.ts
Fixes #383. There were a two things that caused issues attaching to
remote processes:
1. We requested sourcemaps from their remote location, which doesn't
exist locally. This PR rebases the path correctly.
2. We used url length as the heuristic for which to narrow the 'correct'
file at an absolute path. With a different remote root, though, the
urls might be totally different. We now also check whether the
original path is the sourcemap parent of the generated path. This was
the problem in the linked issue, where ts-node was used.
> fix: source handling with remoteRoot

- src/adapter/completions.ts
- src/adapter/debugAdapter.ts
- src/adapter/evaluator.ts
- src/adapter/threads.ts
- src/ioc.ts
- src/test/completion/completion.test.ts
- src/test/evaluate/evaluate-returnvalue.txt
- src/test/evaluate/evaluate.ts
- src/test/extension/nodeConfigurationProvidersTests.ts
Although the return value is not normally accessible to code, from the
CDP perspective it's just an object reference which can be addressed
like any other reference. So with a little bit of legwork, we can make
it work.
In this PR, we preprocess evaluated code looking for the special
$returnValue identifier. When we get it, we trigger logic to 'hoist' the
return value into the global scope by evaluating `globalThis[var] =
this` in the context of the return object, and then replace $returnValue
in the code. We include a timeout to clear the global reference to avoid
polluting the namespace (which could leak memory).
One interesting thing that arises is that we can technically do this for
any internal object. So, for instance, we could similarly allow
accessing the settled value or error on …
> feat: allow usage of $returnValue

- package.json
- scripts/dap-custom.json
- scripts/generate-cdp-api.js
- scripts/generate-dap-api.js
- src/adapter/debugAdapter.ts
- src/adapter/profileController.ts
- src/adapter/profiling/basicProfiler.ts
- src/adapter/profiling/index.ts
- src/adapter/threads.ts
- src/build/strings.ts
- src/cdp/api.d.ts
- src/common/contributionUtils.ts
- src/common/datastructure/observableMap.ts
- src/dap/api.d.ts
- src/dap/errors.ts
- src/extension.ts
- src/ioc-extras.ts
- src/ioc.ts
- src/targets/delegate/delegateLauncher.ts
- src/targets/delegate/delegateLauncherFactory.ts
- src/targets/node/nodeLauncherBase.ts
- src/ui/debugSessionTracker.ts
- src/ui/profiling.ts
- src/ui/profiling/uiProfileManager.ts
- src/ui/profiling/uiProfileSession.ts
- src/ui/ui-ioc.ts
This PR implements basic .cpuprofile capturing for debug sessions.
- Users can start profiling through a context menu on the debug session,
or by running a command from the palette. If there's more than one
session, running a command will open a quickpick to choose the session
to profile.
- They will then be asked what kind of profile they want to record. For
Node.js this will be .cpuprofiles and .heapprofiles. For browsers, it
will allow the newer trace profiles.
- While profiling, the debugger is disabled, like the chrome devtools
does. This removes performance overhead and the ability to hit
breakpoints, which mess with the profile...
- Profiling state is shown in the status bar, and clicking on the entry
will stop profiling and ask the user where they want to save the profile
file. …
> feat: initial work on profiling

- src/adapter/threads.ts
In VS when we stop on a breakpoint, and reload the page, we end up with the JavaScript debugging session in a "running state", and the "root js-debug session" that we use on VS on a paused state, so VS tries to show the call stack of the "root js-debug session" (which doesn't make sense).
The core diagnostic teams suggested us to fix this by making a resume request never fail if we weren't paused when it failed.
> Only fail a resume request if we were paused

- src/adapter/variables.ts
Avoid duplicated this variables in Blazor
This will fix: https://github.com/mono/mono/issues/19306
> Avoid duplicated this variables in Blazor

- src/adapter/threads.ts
- src/binder.ts
- src/statistics/breakpointsStatistics.ts
Fixed three bugs:
1. The statistics weren't sent, because the DA specific telemetry reporter wasn't flushed
2. The hits weren't computed because we weren't calling registerBreakpointsHit
3. The hits were removed after setting a breakpoint, because we re-setted breakpoints with the same ids
> Fix breakpoint statistics

- gulpfile.js
- package-lock.json
- package.json
- src/flatSessionLauncher.ts
So it's easier to understand them on telemetry:
nosources-source-map - A SourceMap is created without the sourcesContent in it. It can be used to map stack traces on the client without exposing all of the source code. You can deploy the Source Map file to the webserver.
from: https://webpack.js.org/configuration/devtool/
> Translate stack traces to typescript

- src/adapter/breakpoints.ts
- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/breakpoints/entryBreakpoint.ts
- src/adapter/threads.ts
- src/common/urlUtils.ts
- src/targets/browser/browserPathResolver.ts
- src/test/breakpoints/breakpointsTest.ts
Webpack has a couple modes where each module in the source file is
emitted in its own `eval` statement. As these modes are generally the
fastest for webpack to produce, they're fairly popular.
The issue is that js-debug pauses on each sourcemapped script it
encounters in order to parse their sourcemaps and set and breakpoints.
Usually on the web, we get one sourcemap per JavaScript file, which we
can parse pretty easily. But in eval mode we get thousands of indiviual,
tiny scripts and sourcemaps that we pause, parse, and resume in series.
Even for a fairly simple app of mine, load times were around 20-30s.
My workaround here is to add a change that detects if the code we're
looking at seems to be from a webpack eval bundle (if we see a data-uri
sourcemap, coming from a script in an eval …
> fix: major performance issues with webpack eval bundles

- src/ui/debugNpmScript.ts
Was fully extracted from bundled `npm` extension.
Ideally it should consume function exposed by by `npm` extension bundled within VS Code, although function exposed from `tasks.ts` but not from whole extension and can't be consumed by `vscode.extensions.getExtension('vscode.npm')` notation.
> Added posibility to run with chosen package manager instead of `npm` only.

- src/adapter/objectPreview/index.ts
We got this unhandled rejection from telemetry:
TypeError: Reduce of empty array with no initial value
at Array.reduce (<anonymous>)
at Object.formatAsTable (index.js:381:58)
at k.slot [as _onConsoleMessage] (threads.js:791:41)
at threads.js:341:17
Using 0 as an initial seed won't change the value when the array has contents, and will avoid the crash when it's empty.
I'm assuming that columnsWidth = 0 makes sense if we don't have any columns.
> Fix reduce failing when array is empty

- src/cdp/webSocketTransport.ts
From the telemetry it seems that we are getting errors on ws.addEventListener('error', reject) that are not of the class error.
Documentation says we get an ErrorEvent which is not an error, see https://github.com/websockets/ws/blob/2e5c01f5b550ae4171d127b0b707ebcec5925cc3/lib/event-target.js#L87
> Update ws errors to be actual errors when possible

- src/common/stringUtils.ts
- src/common/urlUtils.ts
- src/test/common/urlUtils.test.ts
We weren't handling URI encoding of file paths. Also, updated urlToRegex
(which I had copied from the previous debugger) to handle these with
case sensitivity in mind. For the path given in the issue, this produces
a regex like:
```
[fF][iI][lL][eE]:\/\/\/[cC]:\/[fF][oO][oO]\/(?:①|%E2%91%A0)(?:ⅻ|%E2%85%BB|Ⅻ|%E2%85%AB)(?:ㄨ|%E3%84%A8)(?:ㄩ|%E3%84%A9)(?: |%20)(?:啊|%E5%95%8A)(?:阿|%E9%98%BF)(?:鼾|%E9%BC%BE)(?:齄|%E9%BD%84)(?:丂|%E4%B8%82)(?:丄|%E4%B8%84)(?:狚|%E7%8B%9A)(?:狛|%E7%8B%9B)(?:狜|%E7%8B%9C)(?:狝|%E7%8B%9D)(?:﨨|%EF%A8%A8)(?:﨩|%EF%A8%A9)(?:ˊ|%CB%8A)(?:ˋ|%CB%8B)(?:˙|%CB%99)(?:–|%E2%80%93)(?:⿻|%E2%BF%BB)(?:〇|%E3%80%87)(?:㐀|%E3%90%80)(?:㐁|%E3%90%81)(?:䶴|%E4%B6%B4)(?:䶵|%E4%B6%B5)[uU]1(?:\[|%5B)(?:|%EE%80%A5)(?:|%EE%80%A6)(?:|%EE%80%A7)(?:|%EE%80%B8)(?:|%EE%80%B9)(?:\]|%5D)[uU]2(?:\[|%5B)(?:|% …
```
> fix: breakpoints not being set in files with unicode characters

- src/cdp/connection.ts
- src/dap/transport.ts
Now we log this instead:
```
{"tag":"cdp.receive","timestamp":1591302982704,"metadata":{"connectionId":0,"message":{"id":28,"result":{"scriptSource":"<script source>"},"sessionId":"349604CB8C037F470A4BCAFCD223B94C"}},"level":0}
{"tag":"dap.send","timestamp":1591302982706,"metadata":{"connectionId":0,"objectToLog":{"seq":191,"type":"response","request_seq":5,"command":"source","success":true,"body":{"content":"<script source>","mimeType":"text/javascript"},"sessionId":"C9995BF646D2938A47CC5EE7A5673E48"}},"level":0}
```
> Do not print sources in logs

- README.md
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/configuration.ts
- src/targets/browser/browserTargets.ts
- src/targets/browser/launcher.ts
- src/test/test.ts
Now we only kill the tab when the debugging sessions ends by default.
I added an option to keep the existing functionality too in case someone prefers that one.
> Kill only the tab by default

- src/cdp/connection.ts
Handler was crashing when a sourceMapUrl wasn't specified
> Fix logging logic when we don't have sourcemapurl

- src/cdp/connection.ts
The current method we use to ensure cdp handler task ordering is
extremely slow (e.g. limited to ~65 messages/sec) and can cause major
issues when debugging certain projects.
We now use the same fix for this as playwright which is much more
performant, and also corrected the check for node version, since this is
only a problem in < 11.0.0 so we don't use the fix on stable 12.18.0
(which doesn't need it)
> fix: cdp message perf issue

- src/cdp/connection.ts
Addressing @dgozman's [feedback](https://github.com/microsoft/vscode-js-debug/pull/531#discussion_r441134020) about this so that we don't create separate
state for each callback.
> chore: make waitWrapper a single constant

- .vscode/settings.json
- README.md
- src/adapter/objectPreview/contexts.ts
- src/build/dapCustom.ts
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/cdp/api.d.ts
- src/common/promiseUtil.ts
- src/common/urlUtils.ts
- src/configuration.ts
- src/dap/api.d.ts
- src/ioc.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserTargets.ts
- src/targets/browser/webviewAttacher.ts
- src/targets/node/extensionHostLauncher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/node/nodeTarget.ts
- src/targets/sourcePathResolverFactory.ts
- src/targets/targets.ts
- src/test/test.ts
- soft dependency on microsoft/vscode#100242
- fixes microsoft/vscode#100242
With these changes, you can now add `debugWebviews: true` (or a Chrome
configuration object) to an extension host configuration to attach
and debug webviews. It works.
Todo:
- As mentioned, this only works with iframe-based webviews. This is where
VS Code is moving towards and Electron webviews are a different beast
that I don't think it's worth dealing with.
- Currently, it attaches to all webviews in Code instances
- The name of the webview debug sessions is a long URL
This can be most easily fixed by exposing some data in the webview
title, cc @mjbvz. Alternatively, we could have some messaging in a
custom message that the main process can send over to js-debug to tell
it about webviews.
> feat: implement webview debugging

- package.json
- src/common/sourceMaps/codeSearchSourceMapRepository.ts
- src/common/sourceMaps/nodeSourceMapRepository.ts
- src/typings/vscode.proposed.d.ts
Since this requires bumping the vscode engine version, we will want to wait a bit before merging this, otherwise people using stable will not be able to use the extension. I guess we can wait a whole month or dynamically figure out whether Insiders is being used.
> Use ripgrep for outFiles search

- src/common/sourceUtils.ts
This makes breakpoints in the react redux VS template hit as expected
> When multiple mappings are available with same variance, pick the earliest one

- src/targets/browser/frames.ts
We now block pages from executing until we can set all the configuration (breakpoints, exceptions, etc...).
This will make it that we'll hit more breakpoints reliable
> Wait for configuration before resuming pages

- src/adapter/smartStepping.ts
We run into the issue of the debugger pausing on the first line when we have smart stepping turned on for the entry breakpoint.
> don't smart step entry breakpoint

- gulpfile.js
- src/flatSessionLauncher.ts
- src/serverSessionManager.ts
- src/sessionManager.ts
- src/ui/vsCodeSessionManager.ts
- src/vsDebugServer.ts
This change is part of an effort for the VS implementation to move away from flat-session mode, and to as closely as possible follow the VS Code implementation, while sharing as much code as possible to avoid breakages due to divergent implementations.
This change moves most of the debug server creation logic out of vsCodeSessionManager and in to its own class (serverSessionManager), and adds the vsDebugServer entry-point which hosts a debug server without any VS Code API dependencies.
> feat: Create the VS Debug Server mode

- gulpfile.js
- src/adapter/threads.ts
This fixes all the bootloader sources appearing on the "Loaded scripts" list (which the user doesn't care about)
> Skip Bootloader to hide it from users

- src/binder.ts
- src/telemetry/classification.ts
- src/telemetry/unhandledErrorReporter.ts
Visual Studio's telemetry APIs reject properties with exclamation points. Adding back the regular error property name for VS only.
> fix: broken VS error telemetry

- src/test/testRunner.ts
`report` is an asynchronous function and should be awaited otherwise the test coverage might not get written to the disk
> await nyc.report() or no test coverage gets recorded

- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/threads.ts
- src/common/logging/index.ts
- src/common/sourcePathResolver.ts
- src/targets/browser/blazorSourcePathResolver.ts
- src/targets/browser/browserPathResolver.ts
- src/targets/sourcePathResolver.ts
- src/targets/sourcePathResolverFactory.ts
- src/test/browser/blazorSourcePathResolverTest.ts
- src/test/browser/browserPathResolverTest.ts
- src/test/testRunner.ts
Start using absolutePathToUrlRegexp instead of absolutePathToUrl so we can customize the Regexp we use for Blazor scenarios  
@connor4312 If you like this approach, I'll add some unit tests for BrowserSourcePathResolver.absolutePathToUrlRegexp
> Refactoring to create absolutePathToUrlRegexp

- src/build/strings.ts
- src/configuration.ts
- src/targets/browser/constructInspectorWSUri.ts
We need to add a new parameter for the inspectUri to move the BlazorProxy launch out of the project system
> Add new parameter for inspectUri needed to move BlazorProxy out of the project system

- src/test/browser/blazorSourcePathResolverTest.ts
I made the Local scenario test work.
Given that we don't support remote scenarios in Mac and Linux at the moment, I'm just skipping that test.
> Make Blazor source-path-resolver tests work in Mac and Linux

- src/common/urlUtils.ts
Adds source-map support for `vscode-webview-resource://` urls from vscode webviews
> Supports vscode-webview-resource: source maps

- src/binder.ts
This is ONLY for Visual Studio because VS is expecting a response. Shouldn't affect VSCode side functionality
> adding response to pause functionality so Visual Studio doesn't hang

- src/build/strings.ts
- src/ui/configuration/nodeDebugConfigurationProvider.ts
We want to avoid using "New"/"Create" so we control how they're displayed. When tabs come in we'll be dropping the prefix all together.
> Remote 'New' from terminal label

- package-lock.json
- package.json
- src/adapter/cdpProxy.ts
- src/adapter/debugAdapter.ts
- src/build/dapCustom.ts
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/common/contributionUtils.ts
- src/dap/api.d.ts
- src/dap/telemetryClassification.d.ts
- src/extension.ts
- src/ui/requestCDPProxy.ts
Extends `js-debug` to expose its internal CDP connection to other extensions.
This pull request resolves #893.
- A new command `requestCDPProxy` returns websocket connection details to connect to the CDP proxy.
- If `requestCDPProxy` is called the first time, the proxy is created
- Otherwise connection details for the previously created proxy are returned
- The debug adapter holds an instance of the CDP proxy and ensures forwarding of any communication between proxy clients and the CDP connection.
- The proxy and its clients use a basic JSON communication protocol described here: https://github.com/swissmanu/vscode-js-debug-cdp-proxy-api
> CDP Proxy: Allows Other Extensions to Reuse CDP Connection

- src/debugServer.ts
- src/debugServerMain.ts
This change allows callers of debugServerMain.ts to be able to provide
what address the DAP listener will bind to. This prevents random
eavesdroppers from listening into the DAP.
Fixes: #1005
> feat: Allow callers of debugServerMain.ts to specify the host

- src/adapter/debugAdapter.ts
- src/binder.ts
When launching a `pwa-node` process, the debugAdapter's _onInitialize()
method is never called, since the dap registers a listener for the
`'initialize'` message _after_ it has arrived. This causes the Thread's
`dap` to never be resolved, so any thread events (e.g. `'paused'`) are
never sent to the client! This in turn causes VSCode to never realize
that the process is stopped, so the debuggee just waits there,
patiently, forever.
This change stores the `Dap.InitializeParams` on the Binder and then
when the Thread is created, the params are forwarded so that the
DebugAdapter can _onInitialize() correctly and the thread-related events
can flow.
Fixes: #1009
> Ensure that the debugAdapter's _onInitialize() is called

- src/common/urlUtils.test.ts
- src/common/urlUtils.ts
- src/targets/browser/browserPathResolver.test.ts
This is a fix for the urlToRegex issue referenced in #1028 along with 2 new test cases.
I'm making the assumption that any part of `aPath` that has already been escaped should also not have the url decode/encode step done, which seems to match the previous intended behavior. I am also making the assumption that there is no expectation at that point that the portion of the path that needs to be escaped will be a valid file url, especially if escapeReStart is not zero. This seems like a safe assumption given that the escape param only seems to be used from one place that works under those assumptions, but the behavior isn't super intuitive. I didn't want to change too much though, especially since I'm new to this codebase and don't know the history of that method.
> fix: Error when trying to set a breakpoint in index.html

- src/adapter/breakpoints.ts
The current behavior is that the debugger is configured to pause while loading source maps if at least one breakpoint has been set during a debugging session. This has the side effect of switching to the sources tab on page reload even if all breakpoints have since been disabled. This commit removes the automatic pausing of the debugger while loading source maps if there are no longer any active breakpoints. Pausing while source maps are loading should resume if any breakpoints are reenabled or new breakpoints are added. This allows developers keep the benefit of more reliable breakpoints early in program without the drawback of extra pauses when they are not needed.
> feat: disable pause if all breakpoints have been disabled

- src/targets/node/nodeBinaryProvider.ts
Since the said issue is resolved and shipped in 16.4, Suggesting users to downgrade is a bad idea, instead they should be recommended to upgrade to the latest release to resolve this issue.
Reference: https://github.com/nodejs/node/pull/38273
> Node 16.x breakpoint warning resolved in 16.4

- src/build/strings.ts
Adding clarification to the `userDataDir` section to explain that another browser instance cannot be launched if this option has been specified, as is explained [here](https://github.com/microsoft/vscode/issues/120872#issuecomment-816215877).
Closes #1072.
> Update userDataDir option documentation

- src/targets/node/autoAttachLauncher.ts
This fixes the "${workspaceFolder}/**" smart pattern being generated being invalid when there is only one workspace folder.
The bootloader code uses micromatch to compare smart patterns to the script path. One of the default patterns is "${workspaceFolder}/**" and that gets converted into something like "{workspace1,workspace2}/**".
When you only have one workspace it looks like this "{workspace1}/**" and while the micromatch documentation is unclear on that point, in my testing this is not expanded and the braces remain making the match impossible. In practice this makes smart attach not work at all in my case.
This PR simply doesn't include the braces in the generated smart pattern when there is only one workspace folder.
As a workaround you can add a wider pattern. In my case …
> Fixed auto attach smart pattern with one workspace.

- src/ui/companionBrowserLaunch.ts
- src/ui/debugSessionTunnels.ts
- src/ui/requestCDPProxy.ts
- fix #1162 
- changed remote/local address usages in `DebugSessionTunnels` class to conform to vscode api standard as used in `vscode.workspace.openTunnel` api method
> fix: DebugSessionTunnels. Misplaced remote/local port usage

- src/targets/node/bootloader.ts
While working on a `node` PR, I encountered the following error when running tests:
This is thrown by a cleanup phase in some of `node`'s testing setup:
```ts
function leakedGlobals() {
const leaked = [];
for (const val in global) {
if (!knownGlobals.includes(global[val])) {
leaked.push(val);
}
}
return leaked;
}
```
I can, technically, adjust `node`'s checks to be able to add `"$jsDebugIsRegistered"` to the allowlist, but I think it's better to change it here because:
1. It helps keep editor-specific changes out of `node`.
2. If the token string were to change in this library, `node` would have to be changed again.
Overall, the purpose of this PR is to make it a tiny bit easier to work on `node` using `vscode`.
> Update bootloader so that `$jsDebugIsRegistered` not enumerable on global

- src/cdp/webSocketTransport.ts
when a redirect occurs the WebSocket updates the url property so we read that in the error handler and replace http(s): with ws(s): and try one more time to connect
fixes [https://github.com/microsoft/vscode-js-debug/issues/1190](https://github.com/microsoft/vscode-js-debug/issues/1190) here to support previous releases of the Blazor debugger
> Rewrite http redirects to be backward compatible with blazor redirects

- src/ui/edgeDevToolOpener.ts
Fixes https://github.com/microsoft/vscode-edge-devtools/issues/787
Microsoft Edge DevTools extension users expect the `webRoot` and `pathMapping` properties in `launch.json` to apply to file links opened through the Edge DevTools. Today, the Edge DevTools extension only considers the `webRoot` and `pathMapping` properties from its own extension settings. This change plumbs the relevant launc config properties through to the `EdgeDevToolOpener` command so that they are available to the DevTools.
Related: https://github.com/microsoft/vscode-edge-devtools/pull/885
> Pass path mapping config to Edge DevTools opener command

- src/adapter/cdpProxy.ts
We are enabling the console in the [Edge DevTools for VS Code extension](https://github.com/microsoft/vscode-edge-devtools).  For this, we need to track two additional events for replay.
- `Runtime.executionContextCreated`
- We need this to send the execution context to the console in order to evaluate script on the page.
- `Runtime.consoleAPICalled`
- We need to replay console events back to our console when we connect such that the DevTools will retain the console history when attaching to an existing target.
Adding these CDP methods to replay will be helpful for anyone else using the JS-Debug proxy to stand their own console.
> Adding replay messages for console in Runtime domain

- src/adapter/sources.ts
- src/common/sourceMaps/sourceMapFactory.ts
- src/test/breakpoints/breakpoints-configure-source-map-thats-path-mapped.txt
- src/test/breakpoints/breakpointsTest.ts
- testWorkspace/web/pathMapped/app.js
- testWorkspace/web/pathMapped/app.js.map
- testWorkspace/web/pathMapped/app.ts
- testWorkspace/web/pathMapped/index.html
> feat: apply pathMapping when loading sourcemaps

- src/common/sourceMaps/sourceMapFactory.ts
Fixes https://github.com/microsoft/vscode/issues/148864. See my comment on the bottom of an explaination of what changed.
> fix: prefer to parse source map directly before failling back to path mapping

- src/build/generate-contributions.ts
In 877e0ae1957172d905b892d898e52b5322853899 the hoverEvaluation timeout default was changed back to 500ms for undocumented reasons. However, the suggested default when adding the timeout to a `launch.json` wasn't changed back.
> fix: Align hoverEvaluation config suggestion with actual default

- src/adapter/sources.ts
- src/common/sourceMaps/sourceMap.test.ts
- src/common/sourceMaps/sourceMap.ts
- src/common/sourceMaps/sourceMapFactory.test.ts
- src/common/sourceMaps/sourceMapFactory.ts
Indexed source maps, described in https://sourcemaps.info/spec.html#h.535es3xeprgt this should allow users to debug bundled output, like that produced by the closure-compiler when producing bundled output.
Fixes #1260
> Adding support for indexed source maps.

- CHANGELOG.md
- src/adapter/objectPreview/betterTypes.ts
- src/adapter/objectPreview/index.ts
- src/test/evaluate/evaluate-supports-bigint-map-keys-1277.txt
- src/test/evaluate/evaluate.ts
Fixes #1277
One more bug since I had it open. Seems like V8 doesn't always send `unserializableValue`. Prefer it if it does, but try to use the description otherwise (since that seems to always be present)
> fix: bigint previews not working in certain cases

- CHANGELOG.md
- src/cdp/connection.ts
- src/targets/node/extensionHostAttacher.ts
Fixes #1289
We weren't properly attributing child processes in the extension host to
the extension host process that created them. This caused them all to
be treated as if they _were_ the extension host process, so closing
any one of them resulted in the debugger thinking the extension host had
gone away and clearing up all sessions.
> fix: debugged child processes in ext host causing teardown

- CHANGELOG.md
- src/ui/processPicker.ts
> fix: errors thrown in process tree lookup not being visible

- CHANGELOG.md
- src/adapter/debugAdapter.ts
- src/adapter/sources.ts
- src/build/dapCustom.ts
- src/build/generate-contributions.ts
- src/build/strings.ts
- src/common/contributionUtils.ts
- src/dap/api.d.ts
- src/dap/telemetryClassification.d.ts
- src/extension.ts
- src/ui/debugSessionTracker.ts
- src/ui/excludedCallersUI.ts
- src/ui/manageContextKey.ts
- src/ui/prettyPrint.ts
- src/ui/profiling/uiProfileManager.ts
- src/ui/ui-ioc.ts
Fixes https://github.com/microsoft/vscode/issues/151410
Now there's always a `{}` icon (similar to what's in devtools, which is not super expressive, but I don't know of a better icon...) in the title bar of `.js` files when debugging JavaScript.
This should also make things a little faster since this was our last usage of the `DebugAdapterTracker`. Decent negative diff.
> feat: simplify pretty print to align with devtools

- CHANGELOG.md
- src/targets/browser/spawn/endpoints.ts
Fixes https://github.com/microsoft/vscode/issues/144315
> fix: extension debugging not working with two ipv6 interfaces

- CHANGELOG.md
- src/targets/browser/launcher.ts
The stdout buffer can get full, leading to freezes. We didn't hit this with normal browsers, since they don't log very much. Also, when trace logging is turned on, dumpsio=true is used to add info to logs.
> fix: freezes when debugging vscode

- src/build/generate-contributions.ts
- src/common/contributionUtils.ts
- src/ui/configuration/nodeDebugConfigurationProvider.ts
Fixes https://github.com/microsoft/vscode/issues/151910
Depends on https://github.com/microsoft/vscode/pull/151973
> chore: mark prefixed debug types as deprecated

- CHANGELOG.md
- src/adapter/breakpointPredictor.ts
- src/adapter/breakpoints.ts
- src/adapter/threads.ts
- src/cdp/connection.ts
- src/common/sourceMaps/sourceMap.ts
- src/common/sourceMaps/sourceMapFactory.ts
- src/common/sourceMaps/sourceMapRepository.ts
- src/common/sourceUtils.ts
- src/common/urlUtils.ts
- src/test/breakpoints/breakpointsTest.ts
- src/test/common/sourceMapRepository.test.ts
- src/test/node/node-runtime.test.ts
**refactor: improve performance of bp predictor for inline maps**
- Avoid parsing data URIs, since doing so is expensive
- For inline maps, we can hash the map for our cache key instead of using stat+mtime
In VS Code, this reduces the predictor runtime by 25-30%.
**fix: avoid blocking or activating the BP predictor when unnecessary**
Previously, we always waited on the breakpoint predictor unless it was
explicitly disabled. This was unnecessary in two cases:
- If we were able to set an instrumentation breakpoint, this was
redundant since we use that to ensure breakpoints get set before
scripts run.
- We used it even if the source in question was already loaded. This is,
while _technically_ useful if a source was present in multiple scripts
(e.g. present in multiple webpack bundles), …
> performance improvements for setting breakpoints in large projects

- CHANGELOG.md
- src/adapter/completions.ts
- src/test/completion/completion.test.ts
We were just bailing out too soon. VS Code's behavior of reusing previous completions helped hide this bug.
Fixes https://github.com/microsoft/vscode/issues/153651
> fix: completions not returning stack variables

- src/adapter/templates/getStringyProps.ts
This PR fixes #1338 
As mentioned in the vscode repo (see https://github.com/microsoft/vscode/issues/155718#issuecomment-1190550755) it might make sense to doublecheck and avoid using the native toString if the output is `[object *]` and there is a better alternative.
> Double check if native tostring is [object *]

- CHANGELOG.md
- src/adapter/variableStore.ts
For some reason, RN on windows seems to return undefined for the value,
even though js-debug asks for returnByValue. Handle that.
Fixes https://github.com/microsoft/vscode/issues/154976
> fix: windows rn direct debugging

- CHANGELOG.md
- src/adapter/threads.ts
- src/common/urlUtils.test.ts
- src/common/urlUtils.ts
- src/targets/node/nodeBinaryProvider.test.ts
- src/targets/node/nodeBinaryProvider.ts
- src/test/extension/nodeConfigurationProvider.test.ts
- src/ui/configuration/nodeDebugConfigurationResolver.ts
Previously deno required manually configuring runtimeArgs and port
flags, with manual selection of the debug port to use[1]
This adds a little bit of extra logic so that all the necessary
configuration for Deno is automatically wired up whenever the user sets
their runtimeExectuable to `deno`. For example, this now works:
```json
{
"type": "node"
"name": "Launch Program",
"program": "${workspaceFolder}/hello.ts",
"runtimeExecutable": "deno",
"request": "launch",
}
```
Where previously it was:
```json
{
"type": "node"
"name": "Launch Program",
"program": "${workspaceFolder}/hello.ts",
"runtimeExecutable": "deno",
"request": "launch",
"attachSimplePort": "9229",
"continueOnAttach": true,
"runtimeArgs": ["run", "--inspect-brk=127.0.0.1:9229", "--allow-all"]
}
```
~~Note that …
> feat: make deno easier to configure

- CHANGELOG.md
- src/targets/node/killTree.ts
I learned that execSync by default inherits stderr, which caused
warnings to be logged when they shouldn't have been.
Fixes https://github.com/microsoft/vscode/issues/156432
> fix: extraneous warnings when restarting debugging

- src/adapter/objectPreview/contexts.ts
- src/adapter/threads.ts
- src/test/evaluate/evaluate-default.txt
First of all I'm sorry to open a PR and don't open a issue before, we can discuss the solution here and if this is not the right approach I can close this PR.
I have already discussed offline with people from VS team and they told me that they cannot change their side because this could break other clients that implements DAP.
Trying to fix double click in a variable that has more than 100 characteres when debugging from VisualStudio.
As vscode-js-debug extension receives a message from dap like this: 
`{"tag":"dap.receive","timestamp":1659118931254,"metadata":{"connectionId":1,"message":{"type":"request","command":"evaluate","arguments":{"expression":"str","frameId":185,"timeout":1500},"seq":13}},"level":0}`
And there is no context, the default behavior for vscode-js-debug extension is …
> Avoid trimMiddle when double click in a variable from VisualStudio

- CHANGELOG.md
- src/common/urlUtils.ts
- src/ioc.ts
- src/targets/browser/browserTargets.ts
- src/targets/targets.ts
Update to the new CDN URL, and make sure the right path resolver is used
Fixes https://github.com/microsoft/vscode-js-debug/issues/1344
> fix: webview debugging

- CHANGELOG.md
- src/adapter/sources.ts
HMR "replaces" sources at runtime with new sources. V8 doesn't ever
unload parsed scripts, so they stick around but are unused. However, the
debugger wasn't aware of this, so if setting a breakpoint at a given
line it could end up displaying it at the wrong place if using an
outdated version of the file. (The breakpoint would still generally get
hit, since we resolve it to _all_ possible locations, but its display
is wrong).
Now, we add logic that identified webpack "hot reload" scripts. When
they come in, following webpack's logic of replacing any sourcemapped
scripts js-debug tracks with the one from the HMR bundle.
Fixes https://github.com/microsoft/vscode/issues/155331
> fix: improve resolution in Webpack HMR

- src/adapter/portLeaseTracker.ts
- src/common/findOpenPort.ts
- src/serverSessionManager.ts
- src/vsDebugServer.ts
This PR addresses parts of https://github.com/microsoft/vscode-js-debug/issues/1328 by adding a new argument, `host`, that comes after specifying a `port`. When `host` is given, it is being propagated internally to where servers are being created. For backwards compatability reasons:
1. Only a port can still be given.
2. Default listen IP stays the same as previously, both on the initial server and on child session servers.
> Allow specifying host:port on vsDebugServer.ts

- .ci/publish-nightly.yml
- CHANGELOG.md
- README.md
- gulpfile.js
- package.json
- src/binder.ts
- src/configuration.ts
This reverts commit 8363c62bb8205515bfeabea8789aee6b1361ab32, reversing
changes made to 4294f65e087dc3634776478f39d2c8131dd1ab8b.
Currently, users cannot switch to prerelease extensions, and there is also desire to disallow built-in extension updates--currently allowed on insiders--which would make pre-release builds unsuitable for js-debug.
Go back to having a 'nightly' build pending these conversations (and engineering in core to let js-debug have a good prerelease experience).
> Revert "Merge pull request #1361 from microsoft/feat/use-preview-builds"

- src/adapter/templates/readMemory.ts
Memory inspector swapped "E" and "D" nibbles.  
It happened because there was a typo in hex decoding.  
Problem was only with reading memory, written memory was correct.
> Fix hex typo

- src/targets/node/nodeBinaryProvider.ts
- src/targets/node/nodeLauncherBase.ts
[Volta](https://volta.sh/)'s shim relies on the project `package.json` to find the correct node executable version to be used. Because `getVersionText` is not setting `cwd` when calling `node --version`, the shim responds with an error.
This PR fixes that by passing `cwd` all the way to `getVersion`. As far as I've seen, all the other calls `node` get the `cwd` set correctly. This was the only exception.
> Pass cwd to getVersionText

- src/ui/debugLinkUI.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1380
> fix: use preferred debug type in open link

- src/adapter/stackTrace.ts
As in C# static methods doesn't have this object, and this code was adding a null scope.thisObject, then it was throwing an error with this stacktrace:
So we weren't able to see locals of any static method in C#.
> [blazor] When debugging C# code, a static method doesn't have this

- src/ui/configuration/baseConfigurationProvider.ts
I added logic to rename the dynamic type to the "preferred" type (such as from pwa-node to node), but didn't take into account that sometimes the config providers return a different type to their main type. For npm scripts, for example, they return a `node-terminal` type instead of `pwa-node`. Changing the type to `node` resulted in broken configs.
> fix: dynamic debug configs sometimes having the wrong type

- CHANGELOG.md
- package-lock.json
- src/adapter/breakpointPredictor.ts
- src/adapter/breakpoints.ts
- src/adapter/sources.ts
- src/test/sources/sources-supports-nested-sourcemaps-1390.txt
- src/test/sources/sourcesTest.ts
- testWorkspace/nestedSourceMaps/.gitignore
- testWorkspace/nestedSourceMaps/a/main.bundle.js
- testWorkspace/nestedSourceMaps/a/main.js
- testWorkspace/nestedSourceMaps/a/webpack.config.js
- testWorkspace/nestedSourceMaps/b/lib.bundle.js
- testWorkspace/nestedSourceMaps/b/lib.js
- testWorkspace/nestedSourceMaps/b/webpack.config.js
- testWorkspace/nestedSourceMaps/package.json
(This was entered as a bug, and I thought this fruit was slightly lower hanging than it was, hence my investigation in debt week.)
A fairly common scenario is, like in the original issue, someone building a bundled (e.g. with Webpack) application that includes libraries whose sources also exist on disk. In this case, Webpack would include the compiled library files, but not follow the sourcemaps those libraries have for its made bundle sourcemap--unless the source-map-loader is used, which often is not easy since webpack config customization is not always exposed nicely.
This change supports these so-called 'recursive' sourcemaps:
- The breakpoint predictor will try to recursively resolve sourcemaps
- At runtime, if a loaded script has a source map that includes source content (the …
> support nested sourcemaps

- CHANGELOG.md
- src/targets/node/autoAttachLauncher.ts
Now that Node 12 is EOL and its usage is continuing to decrease in VS Code, I think we can loosen the restriction to allow turning auto attach on with spaces in the path.
Previously we would not allow turning on auto attach if there were spaces in the path, and the Node.js version could not be determined exactly (#708).
Fixes https://github.com/microsoft/vscode-js-debug/issues/1392
> chore: loosen restriction around enabling auto attach

- CHANGELOG.md
- src/adapter/console/console.ts
- src/adapter/debugAdapter.ts
- src/adapter/profileController.ts
- src/adapter/profiling/basicCpuProfiler.ts
- src/adapter/profiling/index.ts
- src/adapter/threads.ts
- src/ioc.ts
- src/targets/node/subprocessProgramLauncher.ts
- src/test/profiling/profiling.test.ts
- src/ui/profiling/uiProfileManager.ts
- src/ui/shutdownParticipants.ts
Fixes #1443
By default, the profile is saved (using a date-stamped name) in the workspace folder. If the user gives the profile a name by passing an argument to `console.profile`, then that is appended with .cpuprofile and used instead.
> feat: support console.profile

- CHANGELOG.md
- src/targets/node/subprocessProgramLauncher.ts
Launching NodeJS processes on Windows requires us to handle casing of drive letters carefully because NodeJS is case sensitive.
The already existing utility function `urlUtils.platformPathToPreferredCase()` is used to adjust paths of the executable and the current working directory.
Fixes https://github.com/microsoft/vscode-js-debug/issues/1448
Contributed on behalf of STMicroelectronics
Signed-off-by: Olaf Lessenich <olessenich@eclipsesource.com>
> fix: use platform preferred case in launcher

- src/adapter/sources.ts
Repro:
1. Debug an extension, like the hex editor, which use the 1DS SDK
2. Notice the debugger hard freezes
This is the result of sourcemaps like the following, which reference
themselves in the sourcesContent:
```json
{"version":3,"file":"IChannelControls.js.map","sources":["IChannelControls.js"],"sourcesContent":["\"use strict\";\r\nexport var MinChannelPriorty = 100;\r\n//# sourceMappingURL=IChannelControls.js.map"],"names":[],"mappings":";;;;AAAA;AACA;AACA"}
```
This 'broke' when we added support for nested sourcemap resolution.
> fix: debugger freeze with self-referential sourcemaps

- .ci/publish.yml
Some of our tokens changed which broke automated GH releases. I will toggle it off for this iteration and create the release manually in order to get js-debug out.
> chore: allow disabling gh release to unblock publishing

- src/targets/node/extensionHostAttacher.ts
This might still race if the extension host starts proccesses fast enough, but that's a separate issue
Fixes #1374
> Bump the timeout of setting the auto attach child processes env vars in extensionHost debugging

- CHANGELOG.md
- src/adapter/scriptSkipper/simpleGlobToRe.test.ts
- src/adapter/scriptSkipper/simpleGlobToRe.ts
The default skipFiles for extension host debugging create a pair of
regexes, which compile down to something like:
```
/^(.+(\\/|$))*node_modules\\.asar\\/(.+(\\/|$))*$/i
```
The former part of this regex is a catastrophic lookahead, taking ~250ms
to test against the string included in the unit tests in this PR.
This fixes that and also adds a sanity unit test to ensure regexes run
reasonably fast.
Fixes https://github.com/microsoft/vscode-js-debug/issues/1469
> fix: skipFiles creating catastrophic regexes

- CHANGELOG.md
- src/adapter/breakpoints/entryBreakpoint.ts
Fixes https://github.com/microsoft/vscode/issues/166369
At one point the implementation of _setByUrl changed which broke that.
> fix: perScriptSourcemaps not reliably breaking

- CHANGELOG.md
- src/adapter/completions.ts
- src/adapter/stackTrace.ts
- src/adapter/templates/getStringyProps.ts
- src/adapter/templates/index.ts
- src/adapter/templates/serializeForClipboard.ts
- src/adapter/threads.ts
- src/adapter/variableStore.ts
- src/test/variables/variables-object-customdescriptiongenerator-shows-errors.txt
- src/test/variables/variables-object-customdescriptiongenerator-using-function-declaration.txt
- src/test/variables/variables-object-customdescriptiongenerator-using-statement-syntax.txt
- src/test/variables/variables-object-customdescriptiongenerator-using-statement-with-return-syntax.txt
- src/test/variables/variables-object-customdescriptiongenerator-with-arrays.txt
- src/test/variables/variablesTest.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1433
There were a couple problems:
- TS uses a `customDescriptionGenerator`. Previously this was being invoked on each individual property. I've merged this with the logic we added for custom `toString()` representations, so that we run it only once for an object and return a map of its properties.
- TS has thousands of variables in each scope. We call `Runtime.getProperties` to get scope variables to use in completions. It seems like getProperties, which does not have any 'limit' parameter, is blocking. We still need this to do sensible completions, but now each stacktrace caches its completions instead of getting new ones on every request.
With these changes, there may still be a little REPL stall on the first evaluation (until …
> fix: improve repl/variable/completion performance for TS

- CHANGELOG.md
- src/adapter/resourceProvider/basicResourceProvider.ts
Fixes https://github.com/microsoft/vscode/issues/167353
> fix: add ipv4->6 fallback

- src/common/sourceMaps/renameProvider.ts
Following discussion in https://github.com/microsoft/vscode-js-debug/pull/1419#issuecomment-1352128145
> Revert to old approach, just allow member accesses in sourcemap renames

- CHANGELOG.md
- src/ui/companionBrowserLaunch.ts
> fix: js-debug in the browser showing extraneous error

- .ci/pipeline.yml
- CHANGELOG.md
- src/adapter/breakpointPredictor.ts
- src/common/fileGlobList.ts
- src/common/sourceMaps/codeSearchStrategy.ts
- src/common/sourceMaps/nodeSearchStrategy.ts
- src/test/common/sourceMapRepository.test.ts
Fixes #1479
Relates to https://github.com/microsoft/vscode/issues/168635
Previously, we naively joined all incoming globs together and ran a
single search for them. However, there are two problems:
- vscode's findTextInFiles doesn't really support multiple globs
- **-prefixed negations, like `!**/node_modules/**`, should apply
everywhere, but globbing behavior is to only apply that to the base
path, which led to confusion (#1479)
This PR redoes the logic. If there are N positive globs, we'll do N
searches in parallel, and apply relevant negations to each one.
> fix: better handling of multiple/relative outFiles

- src/targets/browser/blazorSourcePathResolver.ts
- src/test/browser/blazorSourcePathResolverTest.ts
When adding a breakpoint the urlRegex passed to a blazor app for a js app before this PR was:
"[fF][iI][lL][eE]:\\/\\/\\/[tT]:\\/[tT][hH][aA][yY][sS]\\/[oO][fF][fF][iI][cC][eE]-[aA][dD][dD]-[iI][nN]-[sS][aA][mM][pP][lL][eE][sS]\\/[sS][aA][mM][pP][lL][eE][sS]\\/[bB][lL][aA][zZ][oO][rR]-[aA][dD][dD]-[iI][nN]\\/[eE][xX][cC][eE][lL]-[bB][lL][aA][zZ][oO][rR]-[aA][dD][dD]-[iI][nN]\\/[eE][xX][cC][eE][lL]-[bB][lL][aA][zZ][oO][rR]-[aA][dD][dD]-[iI][nN]\\/[pP][aA][gG][eE][sS]\\/[iI][nN][dD][eE][xX]\\.[rR][aA][zZ][oO][rR]\\.[jJ][sS]($|\\?)|[tT]:\\\\[tT][hH][aA][yY][sS]\\\\[oO][fF][fF][iI][cC][eE]-[aA][dD][dD]-[iI][nN]-[sS][aA][mM][pP][lL][eE][sS]\\\\[sS][aA][mM][pP][lL][eE][sS]\\\\[bB][lL][aA][zZ][oO][rR]-[aA][dD][dD]-[iI][nN]\\\\[eE][xX][cC][eE][lL]-[bB][lL][aA][zZ][oO][rR]-[aA][dD][dD]-[iI][nN]\\\\ …
> Fix adding a breakpoint in a JS file while debugging a blazor app

- CHANGELOG.md
- src/common/pathUtils.ts
- src/serverSessionManager.ts
- src/targets/node/nodeLauncherBase.ts
- src/ui/companionBrowserLaunch.ts
- src/ui/vsCodeSessionManager.ts
A debt item I've been meaning to address for a while anyway. Though we still want to support port servers for VS debug.
Should fix https://github.com/microsoft/vscode/issues/169182
> fix: reduce number of ports used by debugger

- CHANGELOG.md
- src/adapter/threads.ts
Found when looking at https://github.com/microsoft/vscode/issues/164124
> fix: provide memory reference for evaluate expressions

- README.md
The marketplace apparently started blocking extension publishing if the
readme includes any svg references. So just delete the star/version badges.
> fix: publishing not working

- CHANGELOG.md
- src/adapter/debugAdapter.ts
- src/adapter/sources.ts
- src/test/sources/sources-basic-source-map.txt
- src/test/sources/sources-basic-sources.txt
- src/test/sources/sources-updated-content.txt
- src/test/sources/sources-url-and-hash.txt
- src/test/sources/sourcesTest.ts
Fixes https://github.com/microsoft/vscode/issues/168013
We don't know if a source type is actually JavaScript. Just let the editor guess instead of reimplementing mimetype detection ourselves
> fix: don't hardcode generated source types as javascript

- src/adapter/debugAdapter.ts
- src/adapter/sources.ts
Fixes https://github.com/microsoft/vscode/issues/168013.
We need to provide a hint for extensionless files that the editor can't guess itself.
> fix: followup for vscode#168013

- src/common/sourceMaps/turboGlobStream.test.ts
- src/common/sourceMaps/turboGlobStream.ts
The turbo glob stream was not using path.sep, so its paths didn't match source files and caused extraneous warnings about symlinks on Windows
> fix: warnings of symlinks on windows

- src/dap/connection.ts
- src/dap/transport.ts
This iteration we moved to named pipes for the connection to VS Code.
This exposed a race that wasn't hit for TCP connections: the destroy
call for streams was being invoked on the next tick after calling
transports' send(), which could be before the write happened.
The result was the DAP terminated() event didn't get sent through so
VS Code was just timing out the session after a second, which looked janky.
> fix: shutdown of debug adapter being slow

- CHANGELOG.md
- src/adapter/console/textualMessage.ts
Fixes https://github.com/microsoft/vscode/issues/172868
This now works as of https://github.com/microsoft/vscode/pull/172880
> fix: support rich ANSI output for complex logs

- CHANGELOG.md
- src/common/sourceMaps/renameProvider.ts
- src/test/breakpoints/breakpoints-logpoints-basic.txt
- src/test/variables/variables-multiple-threads-worker.txt
This reverts commit 7b5e81dbb0c6d4b7d8cbf4de18a46208bb39c6b1, reversing changes made to 6130f21c78719d9934ac4eca682f945a3904fe4e.
Fixes https://github.com/microsoft/vscode-js-debug/issues/1561
Just undo this change (made last release) in this one. I'm not sure if it's possible to support this, at least without changes upstream in Babel.
> Revert "Merge pull request #1481 from microsoft/complex-sourcemap-names"

- CHANGELOG.md
- src/configuration.ts
- src/ui/configuration/extensionHostConfigurationResolver.ts
See https://github.com/microsoft/vscode-js-debug/issues/1554#issuecomment-1420520834
> fix: resolveSourceMapLocations not being auto-filled for ext host debug

- CHANGELOG.md
- src/ui/debugNpmScript.ts
Fixes https://github.com/microsoft/vscode/issues/172522
> fix: don't fail on dynamic config provisioning if no package.json's exist

- .ci/common-validation.yml
- .ci/publish-nightly.yml
- .ci/publish.yml
- CHANGELOG.md
- src/common/pathUtils.ts
- src/targets/sourcePathResolver.ts
- src/test/node/node-source-path-resolver.test.ts
See https://github.com/microsoft/vscode-js-debug/issues/1554#issuecomment-1420520834
Due to some bad logic, we ended up escaping the glob pattern that was meant to find sourcemaps.
> fix: source map resolution in parent workspace folder paths not working

- src/debugServerMain.ts
> fix: Reflect.hasOwnMetadata is not a function in debugServer

- CHANGELOG.md
- src/adapter/breakpoints.ts
- src/adapter/threads.ts
Chrome Dev (112) no longer has any stackframes for instrumentation
breakpoints, which was resulting in a thrown error.
Fixes #1567
> fix: unbound breakpoints in sourcemaps on Chrome 112

- .husky/pre-commit
- CHANGELOG.md
- package.json
- src/adapter/breakpoints.ts
- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/diagnosics.ts
- src/adapter/scriptSkipper/implementation.ts
- src/adapter/sources.ts
- src/adapter/threads.ts
- src/targets/browser/browserLauncher.ts
- src/test/breakpoints/breakpoints-deals-with-removed-execution-contexts-1582.txt
- src/test/breakpoints/breakpointsTest.ts
- testWorkspace/web/iframe-1582/index.html
- testWorkspace/web/iframe-1582/inner.html
- testWorkspace/web/iframe-1582/inner.js
Fixes https://github.com/microsoft/vscode-js-debug/issues/1582
We weren't dealing with removed execution contexts at all (e.g. removing an iframe or worker), only cleared ones (e.g. refreshing the entire page). Now, removing an execution context properly removes its sources, and scripts from multiple contexts are handled.
I think this is also an underlying fix for several other bugs I have open; will investigate tomorrow.
> fix: assorted bad source behaviors when reloading a page

- gulpfile.js
We were copying package.nls.json, but also generating it incorrectly
due to some orphaned code in the migration.
> fix: strings not being included

- src/targets/node/stdStreamTracker.ts
- src/targets/node/subprocessProgramLauncher.ts
Debug console output sometimes gets clumped together when capturing stdout/err instead of console calls since data is sent to DAP as soon as it arrives.
This change changes the behavior do that output is sent to DAP on newlines.
It also looks out for ETX characters and, if it finds those, it switches to sending output to DAP on each ETX. This allows for better handling of multiline log entries.
Fixes https://github.com/microsoft/vscode/issues/175763
> fix: ensure debug console separates output lines

- src/binder.ts
- src/dap/connection.ts
- src/dapDebugServer.ts
- src/debugServer.ts
- src/flatSessionLauncher.ts
- src/targets/browser/browserAttacher.ts
- src/targets/browser/browserLauncher.ts
- src/targets/delegate/delegateLauncher.ts
- src/targets/node/nodeLauncherBase.ts
- src/targets/targets.ts
- src/test/node/node-runtime.test.ts
- src/test/test.ts
- src/vsDebugServer.ts
Previously the `Binder` was a little messy. The binder managed the "tree" of debug sessions, but teardown was not handled in a particular order. So, for example, when terminating a Node.js session with a bunch of child processes, the parent process could be terminated and disconnected while its children were nominally still "running" if their async shutdown logic didn't finish yet.
Now that things are nicely ordered, I can fix this one https://github.com/microsoft/vscode/issues/173993
> refactor: improve and order handling in the `Binder`

- CHANGELOG.md
- src/adapter/resourceProvider/basicResourceProvider.ts
TIL that assigning an invalid value to `url.hostname` silently fails
if invalid.
Fixes https://github.com/microsoft/vscode/issues/167353
> fix: sourcemap lookups on ipv6 localhost addresses

- CHANGELOG.md
- src/common/findOpenPort.ts
- src/test/browser/browser-launch.test.ts
Fixes #1628
Moving to esbuild caused it to pull in the "wrapper.mjs" which doesn't
expose the same API that `ws` normally does.
See https://github.com/websockets/ws/issues/2032#issuecomment-1096945114
> fix: browser debugging in remotes not working

- CHANGELOG.md
- src/targets/node/nodeSourcePathResolver.ts
- src/test/breakpoints/breakpoints-hot-transpiled-avoids-double-pathmapping-1617.txt
- src/test/breakpoints/breakpointsTest.ts
- testWorkspace/tsNode/index.js
Fixes https://github.com/microsoft/vscode-js-debug/issues/1617
If the url in a sourcemap is relative, assume we've already mapped the
compiledPath, and don't map again.
> fix: breakpoints not binding in certain cases if localRoot is a path child of remoteRoot

- gulpfile.js
- src/configuration.ts
Previously, the package.json pulled in at the bundle step was the "nightly"-treated version, but this is no longer the case. This causes nightly to not be able to automatically determine it's running in a remote workspace, since the extensionId is wrong.
Instead, define the version, package name, and publisher as compile-time constants.
Refs https://github.com/microsoft/vscode-js-debug/issues/1628#issuecomment-1492769589
> fix: workspace detection of nightly extension not working

- gulpfile.js
- src/configuration.ts
esbuild can minify syntax as well, and by default it targets esnext,
which caused it to emit null coaslecing. Set the target explicitly
to avoid this.
Fixes https://github.com/microsoft/vscode-js-debug/issues/1624 (again)
> fix: another node 10 fix

- src/adapter/stackTrace.ts
- src/adapter/threads.ts
This was a race that was exposed because we were waiting for scripts in the stacktrace to come in. Turns in Node.js doesn't emit `Runtime.executionContextCreated` for its first context.
Refs https://github.com/nodejs/node/issues/47438
Fixes #1643
> fix: cannot read createScope of undefined

- src/adapter/threads.ts
483425e50cf0fb313610d2346b51459c8db556e2 fixed a race condition, but included a hack to workaround a node bug. But the hack was too specific, and didn't apply to the javascript debug terminal.
> Fix the race for the javascript terminal too

- src/targets/node/nodeWorkerTarget.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1646
> fix: can't hit breakpoints in worker thread that starts before debugger attaches

- CHANGELOG.md
- src/adapter/breakpoints/breakpointBase.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1661
> fix: vite sources on posix not setting breakpoints correctly

- src/cdp/webSocketTransport.ts
fix #1664 which doesn't pass the `remoteHostHeader` arg on redirect error.
> fix remoteHostHeader option for redirect error

- .vscode/launch.json
- CHANGELOG.md
- src/ui/companionBrowserLaunch.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1603
Works with https://github.com/microsoft/vscode-js-debug-companion/pull/24
> fix: ECONNREFUSED when debugging from WSL

- src/adapter/objectPreview/index.ts
backslash which in regexp SHOULD NOT be escaped as a string.
```js
const regArr = [/hello\w+/];
const reg0 = regArr[0];
debugger;
```
> fix: solving the problem of escaped backslashes in regular expressions.

- .ci/publish-nightly.yml
- .ci/publish.yml
- gulpfile.js
- package-lock.json
- package.json
- src/build/generate-contributions.ts
This adds a new build mode where the built assets will replace those in the repo. This can be used in pipelines to avoid having the "workingDir" that doesn't exist until later.
I also looked at modifying the checked-in package.json, but this was difficult because:
(a) we modify the _name_ for nightly builds, which includes local
development, and having this change based on the build is noisy.
(b) there's just a lot of package.json (about 13k lines) which
uncompressed is sizable
> chore: 'hoist' package to reduce pipeline variance

- CHANGELOG.md
- src/adapter/smartStepping.ts
Fixes #1700
A step/pause pair usually takes <3ms, so I think we can be much more generous with our threshold
> fix: increase smart step backout threshold for better stepping

- CHANGELOG.md
- src/common/sourceMaps/turboGlobStream.test.ts
- src/common/sourceMaps/turboGlobStream.ts
The filter was missed in unit testing and didn't actually work correctly. In most cases this didn't lead to a visible failure, but this fixes it.
Fixes #1704
> fix: breakpoints not hitting early on in nested sourcemapped programs

- CHANGELOG.md
- src/adapter/threads.ts
Ref https://github.com/dotnet/runtime/issues/86754
A true fix is being applied in .net, but this will take time to trickle down.
> fix: Blazor sources sometimes being missing

- CHANGELOG.md
- src/adapter/breakpointPredictor.ts
- src/common/pathUtils.ts
- src/test/sources/pretty-print-sources-bps.txt
- src/test/sources/pretty-print.test.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1719
> fix: sourcemap predictor not filtering nested session on windows

- CHANGELOG.md
- src/adapter/threads.ts
Some requests can make the client application run slow. If the user
tries to resume multiple times when paused and "stuck", it's very easy
to get into a bad state.
With this change, coalesce multiple requests of the same type together
so that clicking resume while stalled doesn't tear the state.
I couldn't really get a consistent test case for this since it's
timing based :/
Found while investigating https://github.com/microsoft/vscode-js-debug/issues/1719
> fix: possible bad state when resuming multiple times with a slow client

- CHANGELOG.md
- src/adapter/objectPreview/betterTypes.ts
- src/adapter/objectPreview/index.ts
- src/adapter/variableStore.ts
- src/test/evaluate/evaluate-repl.txt
- src/test/evaluate/evaluate-supports-bigint-map-keys-1277.txt
Objects and sets now show their values under the first expansion instead
of requiring the user to expand an additional level. Also, their
accessors are fixed which allows "copy value" and "copy as expression"/
> fix: improve previews of maps and sets

- gulpfile.js
When building inside VS, watch will lock the build process, which is something we don't want. I instead added a "--debug" mode that will generate sourcemaps and prevent minifying. The usage in general will be `npx gulp vsDebugServerBundle --debug`.
> Add --debug mode to vsDebugServerBundle

- CHANGELOG.md
- src/targets/sourcePathResolver.ts
Didn't seem to actually cause any issues, just noticed and error in the logs.
> fix: runtime error when loading electron preloads

- src/common/pathUtils.ts
- src/ui/processTree/darwinProcessTree.ts
- src/ui/processTree/posixProcessTree.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1752
Also see https://github.com/microsoft/vscode-js-debug/issues/1747
> fix: process picker broken on some Linux distros

- src/adapter/completions.ts
- src/test/completion/completion.test.ts
e.g. `arr.len|`, seems it was broken for years
fixes https://github.com/microsoft/vscode/issues/168021
> fix member expression completions

- src/adapter/threads.ts
Excellent project, I love that it just always works out of the box! Thanks! This is just a minor fix where one of the utility outputs were off by a character.
The output was:
```bash
Output has been truncated to the first 100000 characters. Run `copy(object))` to copy the full output.
```
Which just results in a syntax error:
```bash
Uncaught SyntaxError SyntaxError: Unexpected token ')'
```
> Remove extra bracket from command line copy utility

- package-lock.json
- package.json
- src/targets/node/subprocessProgramLauncher.ts
- src/test/console/console-format-ext-handling.txt
- src/test/console/consoleFormatTest.ts
Previously when supporting EXT we added per-line splitting and emitting,
but we actually should just reemit things immediately unless we see
an EXT.
Fixes https://github.com/microsoft/vscode/issues/181785
> fix: immediately log stdout/err unless EXT is encountered

- src/targets/node/autoAttachLauncher.ts
- src/targets/node/extensionHostAttacher.ts
- src/targets/node/nodeAttacher.ts
- src/targets/node/nodeAttacherBase.ts
- src/targets/node/nodeLauncherBase.ts
- src/test/node/node-runtime.test.ts
> fix: don't overwrite custom NODE_OPTIONS

- CHANGELOG.md
- src/adapter/templates/getStringyProps.ts
- src/adapter/templates/index.ts
- src/adapter/variableStore.ts
- src/test/console/console-format-custom-symbol.txt
- src/test/console/console-format-popular-types.txt
- src/test/console/consoleFormatTest.ts
Fixes https://github.com/microsoft/vscode/issues/102181
> feat: add `Symbol.for("debug.description")` as a way to generate object descriptions

- src/common/sourceMaps/cacheTree.ts
- src/common/sourceMaps/sourceMapRepository.ts
- src/common/sourceMaps/turboGlobStream.test.ts
- src/common/sourceMaps/turboGlobStream.ts
- src/common/sourceMaps/turboSearchStrategy.ts
**Problem**
Debugging experience is slow in large monorepos, since all the files are read to check location of sourcemap file
**PR fix**
Check if .map file exists for compiled file we don't need to read file to find location of sourcemap location. 
**Possible issue**
If there is a js file and it has .map file which is not a sourcemap file with same js file name, it can lead to issue.
This however should be rare edge case.
> Speed up sourcemap lookups by checking existance of .map files

- package-lock.json
- package.json
- src/adapter/dwarf/wasmSymbolProvider.ts
- src/adapter/pause.ts
- src/adapter/smartStepping.ts
- src/adapter/sourceContainer.ts
- src/adapter/stackTrace.ts
- src/adapter/threads.ts
- src/adapter/variableStore.ts
- src/common/positions.test.ts
- src/common/positions.ts
- src/test/breakpoints/breakpoints-user-defined-bp-on-first-line-with-stop-on-entry-on-ts-file-reports-as-breakpoint.txt
- src/test/sources/sources-sourcemap-error-handling-logs-lazy-parse-errors.txt
- src/test/sources/sourcesTest.ts
> This is part 5 in a stacked PR. This will get merged down into a single PR after all of them are reviewed
This is the final part of the initial DWARF debugging work. It implements support for dealing with inlined function calls, such that inline functions appear as normal in the stack, and stepping works. This also improves stepping overall, such that stepping goes between statements rather than assembly instructions.
The [linked docs](https://github.com/ChromeDevTools/devtools-frontend/blob/c9f204731633fd2e2b6999a2543e99b7cc489b4b/docs/language_extension_api.md#dealing-with-inlined-functions) briefly explain how inlined functions work in their API. The largest chunk of code in this PR is refactoring the stacktrace functionality to support these 'fake' callframes.
> feat: implement wasm inline functions

- package-lock.json
- package.json
- src/adapter/dwarf/dwarfModuleProvider.ts
- src/adapter/dwarf/dwarfModuleProviderImpl.ts
- src/adapter/dwarf/wasmSymbolProvider.ts
- src/adapter/pause.ts
- src/adapter/smartStepping.ts
- src/adapter/source.ts
- src/adapter/sourceContainer.ts
- src/adapter/stackTrace.ts
- src/adapter/threads.ts
- src/adapter/variableStore.ts
- src/common/positions.test.ts
- src/common/positions.ts
- src/ioc-extras.ts
- src/ioc.ts
- src/test/breakpoints/breakpoints-user-defined-bp-on-first-line-with-stop-on-entry-on-ts-file-reports-as-breakpoint.txt
- src/test/sources/sources-sourcemap-error-handling-logs-lazy-parse-errors.txt
- src/test/sources/sourcesTest.ts
- src/ui/dwarfModuleProviderImpl.ts
- src/ui/ui-ioc.extensionOnly.ts
> This is part 4 in a stacked PR. This will get merged down into a single PR after all of them are reviewed
This prompts to install the DWARF debugger the first time a user steps into a relevant file. If the debugger is running outside of VS Code (we ship a standalone DAP server that neovim and a few other people use) it just prints a console message asking to install the Node module. For VS Code, it's show as a notification to install the extension that exports the API.
We do this because the DWARF debugging component is about 12MB alone which is not something we want to ship out of the box in VS Code.
> feat: prompt to install extension on wasm step

- package-lock.json
- package.json
- src/adapter/dwarf/dwarfModuleProvider.ts
- src/adapter/dwarf/dwarfModuleProviderImpl.ts
- src/adapter/dwarf/wasmSymbolProvider.ts
- src/adapter/pause.ts
- src/adapter/smartStepping.ts
- src/adapter/source.ts
- src/adapter/sourceContainer.ts
- src/adapter/stackTrace.ts
- src/adapter/threads.ts
- src/adapter/variableStore.ts
- src/adapter/wasmSymbolProvider.ts
- src/common/positions.test.ts
- src/common/positions.ts
- src/ioc-extras.ts
- src/ioc.ts
- src/test/breakpoints/breakpoints-user-defined-bp-on-first-line-with-stop-on-entry-on-ts-file-reports-as-breakpoint.txt
- src/test/sources/sources-sourcemap-error-handling-logs-lazy-parse-errors.txt
- src/test/sources/sourcesTest.ts
- src/ui/dwarfModuleProviderImpl.ts
- src/ui/ui-ioc.extensionOnly.ts
> This is part 3 in a stacked PR. This will get merged down into a single PR after all of them are reviewed
This was a lot of investigation that resulted in an 'oh duh' on figuring out how these were supposed to be done. We just need a little bit of special handling, as in the contained comment.
> feat: make wasm inline breakpoints work

- package-lock.json
- package.json
- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/dwarf/dwarfModuleProvider.ts
- src/adapter/dwarf/dwarfModuleProviderImpl.ts
- src/adapter/dwarf/wasmSymbolProvider.ts
- src/adapter/pause.ts
- src/adapter/smartStepping.ts
- src/adapter/source.ts
- src/adapter/sourceContainer.ts
- src/adapter/stackTrace.ts
- src/adapter/threads.ts
- src/adapter/variableStore.ts
- src/adapter/wasmSymbolProvider.ts
- src/common/arrayUtils.ts
- src/common/positions.test.ts
- src/common/positions.ts
- src/common/sourceMaps/renameProvider.ts
- src/common/urlUtils.ts
- src/ioc-extras.ts
- src/ioc.ts
- src/targets/node/nodeLauncher.ts
- src/test/breakpoints/breakpoints-user-defined-bp-on-first-line-with-stop-on-entry-on-ts-file-reports-as-breakpoint.txt
- src/test/sources/sources-sourcemap-error-handling-logs-lazy-parse-errors.txt
- src/test/sources/sourcesTest.ts
- src/ui/dwarfModuleProviderImpl.ts
- src/ui/profiling/uiProfileManager.ts
- src/ui/ui-ioc.extensionOnly.ts
> This is part 2 in a stacked PR. This will get merged down into a single PR after all of them are reviewed
This commit implements the "variables" view in WebAssembly It introduces new types in the VariableStore that handle WebAssembly (though this is tweaked and cleaned up slightly in a later stack.) The actual call is pretty simple, `listVariablesInScope` on the worker lists variables, and then we can get their properties.
Also, this PR moves the debugger to have a strong preference for setting breakpoints by URL. This makes breakpoints behave better on reload, which is important because there is no instrumentation pause for WebAssembly. Having looked a little in the Chrome debugger, they actually never set breakpoints by script ID any more, so this follows in their footsteps.
> feat: make wasm variable store work

- package-lock.json
- package.json
`del@6.0.0` ships its own types https://github.com/sindresorhus/del/blob/v6.0.0/index.d.ts
Log:
```
npm WARN deprecated @types/del@4.0.0: This is a stub types definition. del provides its own type definitions, so you do not need this installed.
```
> chore: remove redundant type definitions for del

- src/adapter/breakpoints/breakpointBase.ts
Instead of checking the source url when a script is parsed, used the script URL to see if we should removed unmapped breakpoints
> fix: invalid bps not always removed on overlaid file

- src/build/esbuildPlugins.js
The plugin didn't mark acorn as side-effect-free, so the watchdog bundle was trying to import it
> fix: auto-attach/debug terminal not working in nightly

- CHANGELOG.md
- src/targets/node/nodeAttacherBase.ts
Fixes https://github.com/microsoft/vscode/issues/1935510
> fix: envFiles variables appending rather than replacing in attach

- CHANGELOG.md
- src/adapter/breakpoints.ts
- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/source.ts
- src/adapter/threads.ts
- src/test/sources/sources-sourcemap-error-handling-logs-lazy-parse-errors.txt
- src/test/sources/sourcesTest.ts
V8 does not resolve URL-set breakpoints when the script in question only
has that URL via a sourceURL mapping.
I also noticed an issue with per-script entrypoint breakpoints where
another file with the same name, or part of the same name, could
incorrectly remove the entrypoint breakpoint early. It's fine to just
leave the breakpoint around -- can be slightly slower, but better than
missing the breakpoint entirely.
Fixes https://github.com/microsoft/vscode/issues/194988
> fix: eval webpack config breakpoints not setting

- src/adapter/breakpoints/breakpointBase.ts
- src/adapter/source.ts
- src/adapter/threads.ts
For https://github.com/microsoft/vscode/issues/195037\#issuecomment-1759343645
> fix: also use script ID bps if there is a different embeddername

- package.nls.json
- src/adapter/customBreakpoints.ts
- src/adapter/debugAdapter.ts
- src/adapter/threads.ts
- src/build/dapCustom.ts
- src/build/generate-contributions.ts
- src/cdp/api.d.ts
- src/common/contributionUtils.ts
- src/common/objUtils.ts
- src/dap/api.d.ts
- src/dap/telemetryClassification.d.ts
- src/dapDebugServer.ts
- src/debugServer.ts
- src/test/breakpoints/breakpointsTest.ts
- src/ui/customBreakpointsUI.ts
Uses a manually controlled checkbox list, fixes some state erros. Also
handle the recently-deprecated DOMDebugger.setInstrumentationBreakpoint API.
> chore: cleanup custom breakpoint ui

- src/configuration.ts
I've added `'beta'` and `'dev'` to the doc for `IChromiumLaunchConfiguration.runtimeExecutable` as they were missing.
Reference: https://github.com/microsoft/vscode-js-debug-browsers/blob/2c118eff8f9116a85a03b8ebc2c770ac633c4ca6/src/index.ts#L20-L26
> update doc for IChromiumLaunchConfiguration.runtimeExecutable

- src/targets/browser/browserPathResolver.ts
This was causing issues in WASM debugging where files are included from compilation that may not exist on disk. File URIs are absolute, so don't try to use approximate matching even if the absolute path doesn't exist; it's never going to be right.
> fix: don't use approximate matching for file uris in browsers

- src/adapter/threads.ts
- src/test/console/console-format-ext-handling.txt
- src/test/console/consoleFormatTest.ts
In Node 18 this worked, but in Node 20 stepping out of an
instrumentation BP no-op. Instead it seems we can just resume the
debugger and V8 knows to pause at the next real statement.
Fixes #1892
> fix: instrumentation breakpoint in pauseForSourceMap stuck on Node 20

- CHANGELOG.md
- src/adapter/breakpoints/conditions/expression.ts
- src/adapter/exceptionPauseService.test.ts
- src/adapter/exceptionPauseService.ts
- src/adapter/sourceContainer.ts
- src/adapter/threads.ts
- src/test/breakpoints/breakpoints-condition-ignores-error-by-default.txt
- src/test/breakpoints/breakpoints-condition-pauses-on-error.txt
- src/test/breakpoints/breakpointsTest.ts
- src/test/threads/threads-pause-on-exceptions-does-not-pause-on-exceptions-in-internals.txt
- src/test/threads/threadsTest.ts
Fixes https://github.com/microsoft/vscode/issues/195062
> fix: show errors from cond bps, don't pause on internal exceptions

- CHANGELOG.md
- OPTIONS.md
- package-lock.json
- package.json
- src/configuration.ts
- src/targets/sourcePathResolver.ts
Fixes https://github.com/microsoft/vscode/issues/200665
Requires use of my picomatch fork due to https://github.com/micromatch/picomatch/issues/125.
We could alternatively use brace expansion until that's fixed, but that's much less
efficient that using a logical or.
> fix: match mjs and cjs in outFiles by default

- package-lock.json
- package.json
- src/adapter/debugAdapter.ts
I think I turned this off for verification, and it was still in my workspace when I bumped the last js-debug version
> fix: removed support for logpoints 

- src/targets/node/nodeAttacherBase.ts
Restoring the longer timeout which made this the attach subprocesses feature work again for us.
Contributed on behalf of [Swimm](https://swimm.io/)
> Revert the revert of #1464

- src/adapter/objectPreview/index.ts
Fix for issue reported here: https://github.com/microsoft/vscode-js-debug/issues/1967
Some Javascript Debuggee CDP implementations (Hermes) return the a RemoteObject of `type=number` , `value=0` and the `description` and `unserializableValue` fields unset. This causes RemoteObjects with `type=number` and  `value=0` to be rendered  as NaN due to the logic of formatting numbers here:
https://github.com/microsoft/vscode-js-debug/blob/35c4aea8e08be1ab829bf4e4d585433f7e2b7726/src/adapter/objectPreview/index.ts#L477-L484
> Fix formatting of number 0 in remote object when description is not set

- .ci/publish.yml
Replaces the publish task with a 1ES-compliant one.
Verification run: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=263214&view=results
> chore: fix publish pipeline

- CHANGELOG.md
- src/ui/processTree/processTree.ts
Fixes https://github.com/microsoft/vscode/issues/206683
> fix: avoid forcing attach PID into debug mode with default arg

- .ci/publish.yml
I believe APIScan already scans the w32appcontainertokens-xtra77na.node file in the [win32-app-container-tokens pipeline](https://dev.azure.com/monacotools/Monaco/_build?definitionId=449), though I'm not sure why the app container tokens file takes on a longer name in the js-debug VSIX.
> chore: exclude already-scanned file

- CHANGELOG.md
- src/common/sourceMaps/renameProvider.ts
- src/common/sourceMaps/renameScopeAndSourceMap.ts
- src/common/sourceMaps/renameScopeTree.test.ts
- src/common/sourceMaps/renameScopeTree.ts
- src/common/sourceMaps/renameWorker.ts
- src/common/sourceMaps/sourceMap.ts
Reduces the extension-host runtime from about 1600ms on my machine to 2ms. We still parse the source asynchronously, but our application of mappings before was not efficient.
Fixes https://github.com/microsoft/vscode-js-debug#nightly-extension
> fix: improve main-thread performance of source map rename

- CHANGELOG.md
- package-lock.json
- package.json
- src/cdp/rawPipeTransport.ts
- src/common/streamSplitter.test.ts
- src/common/streamSplitter.ts
- src/targets/node/subprocessProgramLauncher.ts
- src/test/extension/pickAttach.test.ts
- src/test/node/node-runtime.test.ts
- src/ui/processTree/baseProcessTree.ts
Please observe this scientific comparison of rename performance in the copilot chat repo:
Closes https://github.com/microsoft/vscode-js-debug/issues/2001
> fix: improve protocol handling performance in all cases

- CHANGELOG.md
- src/ui/debugTerminalUI.ts
Fixes https://github.com/microsoft/vscode/issues/219673
> fix: debug targets orphaned when a detached child starts after a parent exits

- CHANGELOG.md
- src/common/processUtils.ts
- src/targets/browser/launcher.ts
- src/targets/node/subprocessProgramLauncher.ts
Generalizes the formatSubprocessArguments function to all cases. Fixes EINVAL error in selfhost debugging.
> fix: adopt changes required for CVE-2024-27980 patch

- src/configuration.ts
> `cwd` isn't set by default when using clients other than vscode

- .eslintrc.js
- CHANGELOG.md
- src/adapter/evaluator.test.ts
- src/adapter/evaluator.ts
I haven't been quite able to reproduce this, but this is the
explaination I see for https://github.com/microsoft/vscode/issues/221503,
plausibly caused by sourcemap funkiness.
The root cause is that a hover evaluation's scope is being misidentified
as happening in a scope above the one it should actually run in. We then
saw this and thought we should hoist a variable, but don't find a
variable to hoist, and leave the replaced identifier in the expression.
If the scope were not misidentified, then the behavior would have been
identical because the variable would not be defined anyway.
In this PR we replace the identifier back to its original if we don't
find a variable to hoist, and also add logging to help any future
issues.
> fix: hover evaluation incorrectly showing undefined

- CHANGELOG.md
- src/common/terminalLinkProvider.ts
- src/extension.ts
- src/targets/node/terminalNodeLauncher.ts
- src/ui/debugTerminalUI.ts
- src/ui/terminalLinkHandler.ts
- src/ui/ui-ioc.extensionOnly.ts
> feat: support "debug url" in terminals created through the `node-terminal` launch type

- CHANGELOG.md
- src/adapter/clientCapabilities.ts
- src/adapter/debugAdapter.ts
- src/adapter/messageFormat.ts
- src/adapter/objectPreview/index.ts
- src/adapter/templates/getNodeChildren.ts
- src/adapter/threads.ts
- src/adapter/variableStore.ts
- src/common/disposable.ts
- src/dap/api.d.ts
- src/ioc.ts
- src/test/console/console-format-nodes.txt
- src/test/console/console-format-popular-types.txt
- src/test/console/consoleFormatTest.ts
- src/test/evaluate/evaluate-default.txt
- src/test/evaluate/evaluate.ts
- src/test/infra/infra-initialize.txt
- src/test/logger.ts
- src/test/test.ts
- src/test/variables/variables-web-tags.txt
Advertises ANSI styles as proposed in https://github.com/microsoft/debug-adapter-protocol/issues/500,
though it works without them too, just without colors!
Previously the Nodes were displayed as naive objects, so we'd just
list their properties, which was quite useless when trying to get
a handle on the DOM. Now we display their children as the primary
element display, and have "Node Attributes" in a separate section.
Refs https://github.com/microsoft/vscode/pull/227729
Closes https://github.com/microsoft/vscode-js-debug/issues/2076
> feat: improve display of HTML in the debugger

- src/targets/node/nodeAttacherBase.ts
In Deno 2, Deno has a `process` global. Because of this this extension tries to inject environment variables into the process through the inspector using `process.env`. However when running Deno without I/O permissions (the default), accessing process.env.* will show a permission prompt. This is confusing for users, as their code did not trigger this prompt, but the extensions' injected code did.
Because this code doesn't do anything in Deno anyway (because we do not respect `NODE_OPTIONS`), there is no point in running it in Deno at all. This commit disables this injection code path in Deno through environment detection.
> fix: don't inject NODE_OPTIONS in Deno

- src/targets/sourcePathResolver.ts
- src/test/node/node-source-path-resolver.test.ts
> fix: avoid generating extra rebased paths in relative  `rebaseLocalToRemote`

- src/adapter/breakpoints.ts
- src/adapter/threads.ts
- src/test/breakpoints/breakpoints-disables-entrypoint-breakpoint-when-in-file-vscode230201.txt
- src/test/breakpoints/breakpointsTest.ts
Fixes https://github.com/microsoft/vscode/issues/230201
> fix: disable entrypoint breakpoint at first pause in script

- src/sessionManager.ts
Fixes https://github.com/microsoft/vscode/issues/229100
> fix: show the subsession name before the root prefix

- CHANGELOG.md
- src/ui/debugLinkUI.ts
Fixes https://github.com/microsoft/vscode/issues/228950
> fix: only autofill "debug link" input if the hostname resolves

- CHANGELOG.md
- src/adapter/templates/breakOnWasm.ts
- src/adapter/templates/index.ts
- src/adapter/threads.ts
- src/test/wasm/wasm.test.ts
- src/test/wasm/webassembly-dwarf-can-break-immediately.txt
V8 doesn't give us instrumentation breakpoints for WASM, so take a
primitive approach of overwriting WebAssembly compile/instantiate
methods with one that includes a `debugger;` statement after they're
done, and handle those as instrumentation.
Closes https://github.com/microsoft/vscode/issues/230875
> fix: allow hitting breakpoints early in webassembly

- src/adapter/threads.ts
Also only set the WASM breakpoint as-needed when breakpoints exist.
> fix: ignore extra pauses during wasm compilation

- CHANGELOG.md
- src/targets/browser/browserPathResolver.ts
Closes https://github.com/microsoft/vscode-dwarf-debugging-ext/issues/7
> fix: apply sourceMapPathOverrides to file URIs

- src/targets/browser/spawn/endpoints.ts
- src/targets/node/nodeAttacher.ts
Implementation of #2107 
This updates the `nodeAttacher` to use the `remoteHostHeader` configuration option for the initial HTTP requests to retrieve the debugger's websocket URL.
> feat: use `remoteHostHeader` option when looking up websocket address

- src/adapter/threads.ts
I initially thought a microtask boundary was sufficient, but with wasm
breakpoints with no symbols (where we resume synchronously) I observed
that sometimes the queued `resume` would not be dequeued before the
next paused event was handled. So this moves it to a full macrotask.
> fix: use macrotask state boundary in thread statequeue

- src/adapter/threads.ts
Node has a bug where it doesn't report execution contexts properly. We 'backfill' them if we see a script parsed in an unknown execution context, but we didn't handle that in the same way and so didn't set the WASM module pause in the backfilled contexts.
Closes https://github.com/microsoft/vscode/issues/230875
> debug: fix wasm module pauses for Node

- src/adapter/variableStore.ts
> fix: incremental Performance Degradation with session.customRequest("variables") Calls

- src/adapter/threads.ts
Seems like evaluation can sometimes be delayed for a while depending on the target state.
> fix: add a short race timeout for wasm pause handlers

- EXTENSION_AUTHORS.md
- src/extension.ts
- src/ioc-extras.ts
- src/targets/node/terminalNodeLauncher.ts
- src/typings/vscode-js-debug.d.ts
- src/ui/debugTerminalUI.ts
- src/ui/extensionApi.ts
- src/ui/ui-ioc.extensionOnly.ts
This should help the Bun folks work nicely with the js-debug terminal: https://github.com/oven-sh/bun/issues/15223
> feat: add extension API for debug terminal contributions

- CHANGELOG.md
- src/targets/node/nodeSourcePathResolver.ts
- src/test/node/node-source-path-resolver.test.ts
> fix: breakpoints not registered in transpiled file in remoteRoot

- src/common/logging/fileLogSink.ts
- src/common/logging/index.ts
This was a nice idea but in practice leads to corrupted logs with are frustrating when there's already another issue.
> fix: remove log compression

- src/adapter/debugAdapter.ts
- src/build/dapCustom.ts
- src/cdp/api.d.ts
- src/dap/api.d.ts
- src/dap/errors.ts
Introduce originalUrl in GetPreferredUILocationResult to enhance URL retrieval from stack traces.
> Adds originalUrl to GetPreferredUILocationResult

- src/ui/configuration/nodeDebugConfigurationProvider.ts
- src/ui/getRunScriptCommand.ts
This PR add remaining required changes to support use node as npm script runner in VSCode. See microsoft/vscode#234468
> Support usenode as npm script runner

- CHANGELOG.md
- src/adapter/scriptSkipper/implementation.ts
- src/common/logging/logger.ts
- src/ioc-extras.ts
- src/ioc.ts
- src/telemetry/vscodeExperimentationService.ts
- src/ui/ui-ioc.extensionOnly.ts
- Fix the global scriptSkipper event retaining event references
- Work around the non-disposable vscode-tas-client leaking references
- Cleanup the disposable container weakmap after deleting (just makes
heap profiles easier to read)
Fixes #2173, hopefully
> fix: memory leaks between debug sessions

- src/adapter/breakpoints.ts
- src/common/pathUtils.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/2183
> fix: ensure backslash in path when setting breakpoints in windows

- src/targets/node/nodeSourcePathResolver.ts
Matches what we did for https://github.com/microsoft/vscode-dwarf-debugging-ext/issues/7, but for Node too.
Closes #2185
> fix: apply sourceMapPathOverrides to Node, too

- CHANGELOG.md
- src/binder.ts
- src/build/generate-contributions.ts
- src/targets/node/nodeBinaryProvider.ts
It's now good enough to be reasonably useful in Node.js, so turn it on by default. Still have a setting to turn it off.
> chore: experimental networking by default on recent Node versions

- src/adapter/dwarf/wasmSymbolProvider.ts
- src/adapter/templates/writeMemory.ts
The `WasmWorkerFactory` instance caches a single `IWasmWorker` instance but the `dispose` method on the `IWasmWorker` instance still terminates the underlying worker. The effect is that the worker in the `@vscode/dwarf-debugging` terminates on browser page reloads and never re-spawns again until debugging is restarted.
This PR addresses this issue by still caching a single `IWasmWorker` instance but re-spawning it if the previous call to `dispose` caused the _"ref count"_ to reach zero.
Possible related to https://github.com/microsoft/vscode-dwarf-debugging/issues/6
Also fixes `writeMemory` when WASM memory is `SharedArrayBuffer`.
> Fix bug where the WasmWorker instance is disposed but never re-spawned on page reloads + writeMemory when WASM memory is SharedArrayBuffer

- src/adapter/evaluator.ts
- src/adapter/templates/index.ts
- src/adapter/threads.ts
- src/common/positions.ts
Previously the entire expression was always renamed, but this caused some issues with names in our clipboard wrapper script being replaced. This commit adds logic such that only the expressions inserted in the evaluation are renamed.
We should ideally have a shadowing model instead... but this is a fix for now.
> fix: avoid extraneous rename mapping

- src/configuration.ts
Fix the default URL of turbopack to match the content of https://github.com/vercel/next.js/pull/76075.
x-ref: https://github.com/vercel/next.js/issues/77670#issuecomment-2873760418
> chore: Fix default url for turbopack

- .ci/common-validation.yml
- .ci/pipeline.yml
This PR migrates the pipeline onto the 1ES template and also uses the pools in monacotools.
I would like to merge in this PR, create a new pipeline in monacotools, and then create a new PR for any necessary fixes.
> chore: migrate PR pipeline onto 1ES template
