demos/node/.vscode/launch.json, demos/node/crasher.js, src/adapter/sources.ts, src/common/promiseUtil.ts, src/common/sourceUtils.ts, src/targets/browser/browserAttacher.ts, src/targets/browser/browserLauncher.ts, src/targets/node/callback-file.ts, src/targets/node/nodeLauncher.ts, src/targets/node/program.ts, src/targets/node/restartPolicy.ts, src/targets/targets.ts, src/test/testRunner.ts
Stacked on https://github.com/microsoft/vscode-pwa/pull/39, fairly straightforward with the lifecycle refactor.
=> feat: implement restart for node processes

src/adapter/debugAdapter.ts, src/binder.ts, src/dap/connection.ts, src/telemetry/telemetryReporter.ts, src/telemetry/unhandledErrorReporter.ts
Now we report unhandled exceptions and unhandled rejections in telemetry
=> Report unhandled exceptions

src/adapter/sources.ts
In sourcemaps, if you have a function like we do in the webworker
example containing:
```ts
first.onchange = function() {
console.log('hello');
```
...then `function() {\n  ` is a single segment in the sourcemap. When
we try to set a breakpoint at the start of the line containing
`console.log`, the previous behavior resolved the position at the start
of the containing segment, so the breakpoint would get set right
before the `function()` expression rather than the console.log
statement. This PR updates the positioning to prefer the next 
segment, rather than previous segment, when resolving positions.
Sourcemaps also use 0-indexing for columns, which we didn't account
for. I'm not sure if this was causing any issues, but I fixed it here
nonetheless. (Perhaps related to #40.)
=> fix: breakpoints not applying on first line of block statements

README.nightly.md, gulpfile.js, package.json
- Include README in the package
- Adds message to README for nightly
- Tweak wording
=> Tweaks to the gulpfile and nightly build

src/adapter/smartStepping.ts, src/adapter/sources.ts, src/adapter/stackTrace.ts, src/adapter/threads.ts, src/common/logging/index.ts
For #26
With this we will auto-step through lines in files without mappings in files that have sourcemap. For example, code inserted by TS into a transpiled file that doesn't have source lines associated with it. Skipped frames are also grayed out and marked with "skipped by smartStep".
=> Implement smartStep

src/adapter/breakpoints.ts, src/adapter/debugAdapter.ts, src/adapter/stackTrace.ts, src/binder.ts, src/debugServer.ts
Changed warnings in VS for TODOs in the code.
The warning in VS makes it more annoying to debug and try things there.
=> Avoid some VS warnings

src/adapter/breakpointPredictor.ts, src/adapter/breakpoints.ts, src/adapter/sources.ts, src/common/datastructure/mapUsingProjection.ts, src/common/logging/fileLogSink.ts, src/common/objUtils.ts, src/common/pathUtils.ts, src/common/sourceMaps/sourceMapRepository.ts, src/common/urlUtils.ts, src/test/common/localSourceMapRepository.test.ts, src/test/common/mapUsingProjection.test.ts, src/test/common/urlUtils.test.ts, src/test/testIntegrationUtils.ts, src/test/testRunner.ts
Last night I managed to get one of my local projects on Windows, I managed to get into a case where the path casing it was using stopped matching up what was going around in the adapter, which caused a whole assortment of issues. This PR attempts to fix them...
=> Fixes for case sensitivity issues on windows

.ci/common-validation.yml, .ci/pipeline.yml, package-lock.json, package.json, src/cdp/connection.ts, src/cdp/transport.ts, src/targets/node/watchdog.ts, src/telemetry/telemetryReporter.ts, src/test/breakpoints/breakpoints-launched-source-map-set-compiled-2.txt, src/test/breakpoints/breakpoints-launched-source-map-set-compiled.txt, src/test/breakpoints/breakpointsTest.ts, src/test/browser/browser-launch.test.ts, src/test/common/localSourceMapRepository.test.ts, src/test/common/logging.test.ts, src/test/common/urlUtils.test.ts, src/test/console/consoleFormatTest.ts, src/test/evaluate/evaluate.ts, src/test/extension/nodeConfigurationProvidersTests.ts, src/test/infra/infra-initialize.txt, src/test/logger.ts, src/test/node/node-runtime.test.ts, src/test/node/node-source-path-resolver.test.ts, src/test/sources/sourcesTest.ts, src/test/stacks/stacksTest.ts, src/test/test.ts, src/test/testIntegrationUtils.ts, src/test/testRunner.ts, src/test/threads/threadsTest.ts, src/test/variables/variablesTest.ts
Fix some flakiness, disable failing tests, and hook up test results view in Azure Pipelines
Fix #28
=> Enable tests in CI

src/targets/browser/browserAttacher.ts, src/targets/browser/browserLauncher.ts, src/targets/browser/browserTargets.ts, src/targets/browser/launcher.ts, src/targets/node/killTree.ts
Fixes launching electron apps where closing the browser window is a no-op.
=> fix: close browser tree forcefully on exit

src/adapter/threads.ts, src/int-chrome/adapter.test.ts, src/test/breakpoints/breakpoints-configure-remove.txt, src/test/breakpoints/breakpoints-configure-script.txt, src/test/breakpoints/breakpoints-configure-source-map-predicted.txt, src/test/breakpoints/breakpoints-configure-source-map.txt, src/test/breakpoints/breakpoints-launched-inline.txt, src/test/breakpoints/breakpoints-launched-overwrite.txt, src/test/breakpoints/breakpoints-launched-remove.txt, src/test/breakpoints/breakpoints-launched-script.txt, src/test/breakpoints/breakpoints-launched-source-map-remove.txt, src/test/breakpoints/breakpoints-launched-source-map-set-compiled-2.txt, src/test/breakpoints/breakpoints-launched-source-map.txt, src/test/node/node-runtime-child-processes-debugs.txt, src/test/node/node-runtime-reads-the-envfile.txt, src/test/node/node-runtime-sets-arguments.txt, src/test/node/node-runtime-sets-environment-variables.txt, src/test/threads/threads-stepping-basic.txt, src/test/threads/threads-stepping-cross-thread-constructor-source-map.txt, src/test/threads/threads-stepping-cross-thread-constructor.txt, src/test/threads/threads-stepping-cross-thread-skip-over-tasks.txt, src/test/threads/threads-stepping-cross-thread-source-map.txt, src/test/threads/threads-stepping-cross-thread.txt, src/test/variables/variables-setvariable-scope.txt
The only way to tell the difference between "debugger" and a step is to keep track of whether the user asked to step.
=> Fix pause reason for debugger statement

src/adapter/smartStepping.ts, src/adapter/sources.ts, src/adapter/stackTrace.ts, src/adapter/threads.ts, src/test/breakpoints/breakpointsTest.ts, src/test/stacks/stacks-smartstep.txt, src/test/stacks/stacksTest.ts, testWorkspace/web/async-ts/test.js, testWorkspace/web/async-ts/test.js.map, testWorkspace/web/async-ts/test.ts, testWorkspace/web/async-ts/tsconfig.json
=> Fix smartStep in ignored sourcemaps, add test

demos/node/.vscode/launch.json, src/targets/browser/launcher.ts, src/targets/node/extensionHostAttacher.ts, src/targets/node/nodeAttacher.ts, src/test/node/node-runtime-attaching-retries-attachment.txt, src/test/node/node-runtime.test.ts
=> feat: retry nodejs attachment

src/adapter/breakpoints.ts
Fairly straightforward: when we get a breakpoint request, we compare
against the existing breakpoints in the file, and don't touch any that
remain.
I also made a modification to have us wait for the initial breakpoint
`set()` before returning the breakpoint response, so that points are
resolved from the outset. VS Code doesn't move around breakpoints after
the first response comes back, so this allows the column or line to be
adjusted as in the v1 adapters. (This lack of movement was causing https://github.com/microsoft/vscode-pwa/issues/156)
Fixes https://github.com/microsoft/vscode-pwa/issues/155 and https://github.com/microsoft/vscode-pwa/issues/156
=> feat: implement differential breakpoints

package.json, src/common/contributionUtils.ts, src/extension.ts, src/ui/customBreakpointsUI.ts
=> feat: selectively show the browser bp view, add create button

.vscode/settings.json, src/adapter/threads.ts, src/dap/connection.ts, src/dap/errors.ts, src/targets/browser/browserTargets.ts, src/targets/node/nodeTarget.ts, src/test/evaluate/evaluate-repl.txt, src/test/evaluate/evaluate.ts
instead of sending all results as OutputEvents.
Fix #184
=> Evaluate request should return a real evaluate response,

src/common/sourceMaps/codeSearchSourceMapRepository.ts, src/test/common/sourceMapRepository.test.ts
I'm guessing it works for you because the window running the tests opens a folder. For me it's empty so that search method won't search any folder.
=> Fix failing test

src/adapter/breakpoints/userDefinedBreakpoint.ts, src/common/sourceUtils.ts, src/test/breakpoints/breakpoints-logpoints-basic.txt, src/test/breakpoints/breakpointsTest.ts
=> Change logpoints to work the same as in v1

src/configuration.ts, src/dap/connection.ts, src/targets/browser/browserLauncher.ts, src/targets/browser/browserProcess.ts, src/targets/browser/browserTargets.ts, src/targets/browser/launcher.ts, src/targets/browser/unelevatedChome.ts, src/targets/node/program.ts
* Added support to launch Chrome unelevated in VS
* Fixed enqueueRequest because it was using the wrong seq number
=> Added support to launch Chrome unelevated in VS

src/test/npmScriptLens/npmScriptLens.test.ts, src/ui/npmScriptLens.ts
=> Only get root level scripts property for codelens

src/adapter/breakpoints/breakpointBase.ts
When we set a breakpoint without sources being available, we also assume that it can be a file path instead of a file hosted on a web service
=> Fix blazor bps

src/adapter/threads.ts, src/targets/browser/browserTargets.ts, src/targets/node/nodeAttacherBase.ts, src/targets/node/nodeLauncher.ts, src/targets/node/nodeTarget.ts, src/targets/targets.ts, src/test/node/node-runtime-inspect-flag-handling-treats-inspect-brk-as-stoponentry.txt, src/test/node/node-runtime-stoponentry-launches-and-infers-entry-from-args.txt, src/test/node/node-runtime-stoponentry-sets-an-explicit-stop-on-entry-point.txt, src/test/node/node-runtime-stoponentry-stops-with-a-program-provided.txt
Return entry for stop on entry breakpoints.
VS relies on the reason to auto-resume this breakpoint when needed
=> Return entry for stop on entry breakpoints

src/targets/node/nodeLauncher.ts
Adding Edge to the check that enables debugging node with a browser
=> adding Edge as an option to allow debugging edge with node

src/telemetry/classification.ts
For VS we'll send the exact commit id in the telemetry messages
=> Send commit id in telemetry

src/cdp/connection.ts
We are getting a lot of this on telemetry, and it's not clear why. Hopefully getting the method will help us understand what is happening
=> Improve error message

package-lock.json, src/adapter/threads.ts
In telemetry we got:
TypeError: Invalid value used as weak map key
at WeakMap.set (<anonymous>)
at k._onPaused (threads.js:511:34)
My guess is that while we await this._smartStepper.shouldSmartStep(pausedDetails)
For some reason the app resumes (maybe the user reloads the page, or uses Chrome DevTools), so this._pausedDetails becomes undefined and this._pausedDetailsEvent.set(pausedDetails, event); fails because undefined can't be a key of a WeakMap.
Assuming that's happening, this fix should address that issue
=> Fix possible race condition

src/targets/browser/browserAttacher.ts, src/targets/browser/launcher.ts
Adding support for inspectUri (for Blazor) in attach.
=> fix: Blazor attach (add support for inspectUri in attach)

src/cdp/connection.ts
Don't print sourceMapUrls that are data
=> Don't print sourceMapUrls that are data

src/cdp/connection.ts
I was able to reproduce the unknown session issue #486 . We were getting messages about a session after it has been disposed.
I don't know if this solves all cases of unknown session or not.
=> Partial fix for unknown session

src/adapter/selfProfile.ts, src/binder.ts, src/build/dapCustom.ts, src/cdp/api.d.ts, src/dap/api.d.ts, src/dap/telemetryClassification.d.ts
Let me know if this works for you.
vsix for dev: https://memes.peet.io/img/77307b19-3414-4371-aaf1-e431e7b56cf9.vsix
=> feat: add self-profile commands for vs

src/adapter/sources.ts
Fix angular having absolute paths for all files in VS
=> Fix angular long path issues in VS

gulpfile.js, package-lock.json, package.json, src/targets/node/terminalProgramLauncher.ts
@digeff let me know if this works for you. 
Note that this is behind https://github.com/microsoft/vscode-nls-dev/pull/27 for detecting locales in the compiled files right now.
=> feat: add localization step for vs

src/common/hash/index.ts
Feedback from: https://github.com/microsoft/vscode-js-debug/pull/532
=> Handler hasher process exit

package-lock.json, src/adapter/debugAdapter.ts
Chrome cannot answer some APIs when the target is paused. Do not block on exception pause before configurationDone to avoid the API getting stuck.
=> Do not block on exception pause before configurationDone

src/adapter/breakpoints.ts
Do not block on source-map processing if there are no breakpoints
=> Do not block on source-map if there are no breakpoints

src/common/objUtils.ts, src/configuration.ts, src/targets/node/extensionHostAttacher.ts, src/targets/node/nodeAttacher.ts, src/targets/node/nodeAttacherBase.ts, src/targets/node/nodeLauncher.ts, src/targets/node/nodeLauncherBase.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/584
=> fix: use legacy attachment mode for dealing with --inspect-brk

src/adapter/debugAdapter.ts
We were hitting an undefined exception on VS because this.breakpointManager was undefined in this._onSetBreakpoints
=> Fix undefined exception on VS

src/binder.ts
Fixing a race condition that can leave dangling debug sessions (i.e. debug sessions which have no active CDP target, but don't yet know it).
=> fix: race condition which leaves dangling debug sessions

.vscode/launch.json, src/common/fsUtils.ts
* Added Debug Server (VS Server) to launch the new VS server mode
* Fix some case sensitive issues on remote file system logic
=> Fix Remote FileSystem case sensitivity issues

src/targets/node/bootloader.ts
Fixes https://github.com/microsoft/vscode/issues/108222
=> Debugger does not work when running Node.js on an unsupported operating system

src/build/strings.ts
See also https://github.com/npm/cli#is-it-npm-or-npm-or-npm
=> Use correct spelling of npm

package.json
This extension will be disabled in virtual workspace (remote hub)
=> adopt virtual workspaces

src/targets/node/terminalProgramLauncher.ts, src/test/node/node-runtime.test.ts
=> 990 - Support using launch configuration name as terminal title

src/adapter/cdpProxy.ts, src/adapter/debugAdapter.ts
=> Implements replay of paused events.

src/adapter/variableStore.ts, src/common/stackTraceParser.test.ts
Added some tests for the stacktrace parser while looking into another issue.
And a simple fix https://github.com/microsoft/vscode-js-debug/issues/1221
=> add stacktrace parser test, fix descriptor output

src/build/generate-contributions.ts
Fixes https://github.com/microsoft/vscode/issues/141157
=> fix: only enter debug mode on f11 when debug view is visible

.ci/pipeline.yml, .vscode/settings.json, src/targets/node/nodeSourcePathResolver.ts, src/targets/sourcePathResolver.ts, src/test/breakpoints/breakpoints-ignores-source-url-query-string-1225.txt, src/test/breakpoints/breakpointsTest.ts, testWorkspace/sourceQueryString/output.js
Fixes https://github.com/microsoft/vscode-js-debug/issues/1225
Fixes https://github.com/microsoft/vscode/issues/147662
=> fix: remove query strings from sourcemapped URLs

src/build/generate-contributions.ts, src/build/strings.ts
=> More explicit DA names

CHANGELOG.md, src/targets/node/nodeBinaryProvider.test.ts, src/targets/node/nodeBinaryProvider.ts
=> fix: snap versions in alternate install locations resulting in warning

src/build/generate-contributions.ts, src/build/strings.ts
=> Add unverified breakpoint message

src/test/extension/nodeConfigurationProvider.test.ts, src/ui/configuration/nodeDebugConfigurationResolver.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1288
=> feat: try to load common entrypoint on f5

OPTIONS.md, src/configuration.ts
=> fix: add default webpack path mapping for scoped packages

src/adapter/templates/getStringyProps.ts, src/adapter/variableStore.ts, src/test/console/console-format-custom-tostring.txt, src/test/console/consoleFormatTest.ts
Last minute fix and not thorough enough tests 🤦
=> fix: custom toSTring format not applying to nested props

OPTIONS.md, src/build/generate-contributions.ts, src/build/generateDap.ts, src/build/strings.ts, src/cdp/api.d.ts, src/cdp/telemetryClassification.d.ts, src/common/arrayUtils.ts, src/configuration.ts, src/dap/api.d.ts, src/targets/node/nodeLauncher.ts, src/targets/node/processLauncher.ts, src/targets/node/terminalProgramLauncher.ts, src/test/runTest.ts
=> Adopt argsCanBeInterpretedByShell

CHANGELOG.md, src/targets/browser/browserPathResolver.test.ts, src/targets/browser/browserPathResolver.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1308
=> fix: allow overriding resolution of workspaceFolder in pathMapping

src/ui/configuration/baseConfigurationProvider.ts
=> fix: use preferred names when providing initial configs

CHANGELOG.md, src/adapter/console/exceptionMessage.ts, src/adapter/console/textualMessage.ts, src/adapter/threads.ts, src/test/console/console-format-popular-types.txt
Fixes https://github.com/microsoft/vscode/issues/142197
=> fix: stack traces logged immediately before exit not being sourcemapped

.ci/pipeline.yml, package-lock.json, package.json, src/adapter/breakpoints/breakpointBase.ts, src/test/node/node-runtime-sets-arguments.txt, src/test/node/node-runtime.test.ts
A race was causing a ~10% failure in a test, and could have caused some
failures for users in edge cases (where rarely stepping into the
first function or class declaration in a file would not work.)
Also a janitorial update of Node and pipeline OS images.
=> fix: race in entrypoint breakpoints

CHANGELOG.md, src/cdp/webSocketTransport.ts, src/targets/node/autoAttachLauncher.ts, src/targets/node/program.ts, src/targets/node/watchdogSpawn.ts, src/test/infra/infra-initialize.txt
Fixes [#156810](https://github.com/microsoft/vscode/issues/156810)
=> fix: request loop on certain kinds of Node.js attach failures

CHANGELOG.md, src/adapter/breakpoints/breakpointBase.ts
=> fix: breakpoints not being removed during startup

src/build/generate-contributions.ts
See https://github.com/microsoft/vscode/pull/161326
=> uiMessages -> strings, for microsoft/vscode#153842

.ci/publish-nightly.yml, .ci/publish.yml
Since this module is a built-in module and the strings will be covered by language packs
=> Use `l10nShouldProcess: false`

OPTIONS.md, src/build/documentReadme.ts
=> docs: remove pwa- prefix in OPTIONS.md

src/adapter/breakpoints.ts, src/adapter/breakpoints/userDefinedBreakpoint.ts, src/test/breakpoints/breakpointsTest.ts
=> fix: breakpoint event being sent after disabling

CHANGELOG.md, src/adapter/templates/serializeForClipboard.ts, src/test/evaluate/evaluate.ts
Fixes https://github.com/microsoft/vscode/issues/162747
=> fix: copying a date object resulting in an empty object

CHANGELOG.md, src/common/pathUtils.ts, src/common/urlUtils.test.ts, src/common/urlUtils.ts, src/test/node/node-source-path-resolver.test.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1148
=> fix: properly handle UNC paths

src/configuration.ts
=> fix: resolveSourceMapLocations not deriving from outFiles in debug terminal

CHANGELOG.md, src/adapter/templates/getStringyProps.ts, src/adapter/threads.ts, src/adapter/variableStore.ts, src/test/console/console-format-popular-types.txt, src/test/console/consoleFormatTest.ts
For https://github.com/microsoft/vscode/issues/155142 and https://github.com/microsoft/vscode/issues/154479
=> Longer console length limits

CHANGELOG.md, src/adapter/variableStore.ts
=> fix: private properties in Blazor apps not grouping correctly

CHANGELOG.md, src/adapter/sources.ts, src/adapter/threads.ts
=> fix: js files with sourceURLs opening readonly versions

CHANGELOG.md, package-lock.json, package.json
=> fix: support launching chrome dev/beta as default fallbacks

src/adapter/resourceProvider/basicResourceProvider.ts
Whoops. Some code I couldn't test locally.
=> fix: typo in network fallback

package-lock.json, src/common/hash/index.ts, src/diagnosticTool/index.ts, src/targets/node/autoAttachLauncher.ts, src/targets/node/bundlePaths.ts
Started refactoring stuff with the l10n migration, but aborted them and forgot to undo all the changes
=> fix: build error

CHANGELOG.md, src/adapter/templates/index.ts, src/adapter/templates/invokeGetter.ts, src/adapter/variableStore.ts, src/test/evaluate/evaluate-default.txt, src/test/evaluate/evaluate.ts
=> fix: expansion of non-primitive getters not working

src/dap/errors.ts, src/targets/node/nodeBinaryProvider.ts
=> fix: misleading error for DAP-based consumers on missing cwd

src/build/generate-contributions.ts
=> fix: only show pretty print actions when debugger is stopped

package.json, src/build/generate-contributions.ts
For https://github.com/microsoft/vscode-internalbacklog/issues/3442
=> chore: remove implicit activation events

CHANGELOG.md, src/adapter/evaluator.ts, src/test/variables/variables-setvariable-name-mapping.txt, src/test/variables/variablesTest.ts, testWorkspace/web/minified/index.html
=> fix: repl stacktrace with renames showing too much info

CHANGELOG.md, src/adapter/console/reservationQueue.test.ts, src/adapter/sources.ts
Fixes https://github.com/microsoft/vscode/issues/169733
=> fix: recursive source map resolution parsing ignored locations

src/adapter/objectPreview/betterTypes.ts, src/adapter/objectPreview/index.ts
=> fix: function previews not working in RN/hermes

CHANGELOG.md, src/adapter/debugAdapter.ts, src/adapter/threads.ts, src/targets/node/nodeTarget.ts, src/test/breakpoints/breakpoints-does-not-interrupt-stepover-with-instrumentation-breakpoint-1556.txt, src/test/breakpoints/breakpointsTest.ts, src/test/variables/variables-setvariable-setexpression.txt
=> fix: step over eval/new Function with sourcemaps not working

src/adapter/stackTrace.ts
=> fix: undefined sources with running without debugging

CHANGELOG.md, src/targets/node/bootloader/filters.ts
=> fix: 'break on caught exceptions' pausing on worker threads

src/adapter/profileController.ts, src/ui/autoAttach.ts
Also fixes profiles not saving in auto attach.
Fixes #1492
=> fix: allow saving multiple named profiles

src/dapDebugServer.ts
=> fix: cannot get dapDebugServer actually running the process

src/common/urlUtils.ts
=> fix: never attach to devtools pages

src/adapter/threads.ts
=> fix: do not to translate "promise rejection"

src/adapter/resourceProvider/basicResourceProvider.ts, src/test/sources/sources-sourcemap-error-handling-logs-initial-parse-errors.txt, src/test/sources/sourcesTest.ts
=> perf: fallback should optimistically pick a new hostname when it falls back

src/adapter/breakpoints/conditions/hitCount.ts, src/test/breakpoints/breakpoints-hit-count-implies-equal-1698.txt, src/test/breakpoints/breakpointsTest.ts
=> fix: condition breakpoints not setting with implied =

CHANGELOG.md, src/targets/node/terminalNodeLauncher.ts
=> fix: terminal launches sometimes sending commands too soon

package.json, src/targets/node/autoAttachLauncher.ts, src/typings/vscode.d.ts, src/typings/vscode.proposed.portsAttributes.d.ts
=> chore: adopt EnvironmentVariableCollection.description

src/targets/node/bootloader.ts
=> fix: show bootloader errors without stack

CHANGELOG.md, src/targets/browser/browserPathResolver.ts, src/test/breakpoints/breakpoints-sets-file-uri-breakpoints-predictably-1748.txt, src/test/breakpoints/breakpointsTest.ts
Fixes https://github.com/microsoft/vscode-js-debug/issues/1748
=> fix: set breakpoints predictably when launching with files

CHANGELOG.md, src/targets/node/terminateProcess.sh
=> fix: child process tree not terminating on all Linux distros

src/targets/node/autoAttachLauncher.ts
=> fix: be more specific with EnvironmentVariableCollection.description

CHANGELOG.md, src/adapter/sources.ts
Fixes https://github.com/microsoft/vscode/issues/181746
=> fix: hint content type for sources with query strings

CHANGELOG.md, src/adapter/sources.ts
=> fix: support vite HMR source replacements

CHANGELOG.md, src/adapter/threads.ts
=> chore: trigger perScriptSourceMaps for vite dev server

CHANGELOG.md, src/adapter/debugAdapter.ts, src/binder.ts, src/targets/node/nodeAttacher.ts, src/targets/node/nodeLauncherBase.ts, src/targets/targets.ts, src/test/infra/infra-initialize.txt
=> feat: adopt supportTerminateDebuggee for browsers and node

src/targets/node/bootloader.ts
=> fix: ensure ELECTRON_RUN_AS_NODE is set for the watchdog

CHANGELOG.md, src/ui/requestCDPProxy.ts
Fixes https://github.com/microsoft/vscode/issues/193110
=> fix: edge devtools incorrectly ask for local forwarding

CHANGELOG.md, src/build/generate-contributions.ts
Fixes https://github.com/microsoft/vscode/issues/194190
=> fix: source map stepping registered multiple times

src/adapter/resourceProvider/statefulResourceProvider.ts
=> fix: authentication sourcemap fallback failing for some maps

src/configuration.ts
Fixes https://github.com/microsoft/vscode/issues/194146
=> fix: allow setting breakpoints in common wasm languages

src/adapter/dwarf/wasmSymbolProvider.ts, src/adapter/stackTrace.ts, src/adapter/threads.ts, src/test/variables/variables-object-simple-array.txt, src/test/wasm/wasm.test.ts, src/test/wasm/webassembly-dwarf-does-lldb-evaluation.txt
Fixes https://github.com/microsoft/vscode/issues/194232
=> fix: delegate wasm evaluation with dwarf

CHANGELOG.md, src/adapter/variableStore.ts, src/test/variables/variables-map-variable-without-preview-1824.txt, src/test/variables/variablesTest.ts
=> fix: error when processing private properties with a map

src/adapter/breakpoints.ts
=> fix: handle getPossibleBreakpoints response from hermes

src/adapter/objectPreview/index.ts
Closes a false positive issue.
=> Add suppression comments

CHANGELOG.md, src/adapter/dwarf/wasmSymbolProvider.ts, src/adapter/profileController.ts, src/ioc.ts, src/test/testIntegrationUtils.ts
=> fix: reuse the webassembly worker across sessions in the debug tree

CHANGELOG.md, src/adapter/source.ts, src/targets/browser/vscodeRendererAttacher.ts, src/ui/configuration/extensionHostConfigurationResolver.ts
Fixes https://github.com/microsoft/vscode/issues/196781
=> fix: respect sourceMapResolveLocations in the web extension host

CHANGELOG.md, src/diagnosticTool/breakpointHelper.tsx
Fixes https://github.com/microsoft/vscode/issues/195891
=> fix: path diff display in diagnostic tool

CHANGELOG.md, src/build/generate-contributions.ts, src/ui/configuration/chromiumDebugConfigurationProvider.ts, src/ui/configuration/nodeDebugConfigurationResolver.ts
Fixes https://github.com/microsoft/vscode/issues/192014
=> fix: allow variable substitutions for ports properties

CHANGELOG.md, src/targets/browser/browserLauncher.ts, src/targets/browser/launcher.ts, src/targets/browser/remoteBrowserLauncher.ts, src/targets/browser/spawn/endpoints.ts
Fixes https://github.com/microsoft/vscode/issues/174033
=> fix: automatically reconnect when debugging browsers in port mode

package-lock.json, package.json, src/adapter/templates/getStringyProps.ts
=> fix: avoid unnecessary exceptions in object preview evaluation

src/targets/sourcePathResolver.ts, src/test/extension/nodeConfigurationProvider.test.ts
=> fix: bad regex in matching resolveSourceMapLocations

src/adapter/profiling/basicCpuProfiler.ts, src/adapter/profiling/basicHeapProfiler.ts, src/adapter/profiling/heapDumpProfiler.ts, src/ui/profiling/uiProfileManager.ts
=> Mention VS Code in profile descriptions

src/configuration.ts
This is okay now that we have fcc2ab2
Fixes https://github.com/microsoft/vscode/issues/202057
=> fix: apply resolveSourceMapLocations in remoteRoot

CHANGELOG.md, src/adapter/scriptSkipper/implementation.ts, src/adapter/scriptSkipper/simpleGlobToRe.ts, src/common/urlUtils.ts, src/test/node/node-runtime.test.ts, src/test/stacks/stacks-skipfiles-handles-special-chars-in-stack-203408.txt, src/test/stacks/stacksTest.ts
Fixes https://github.com/microsoft/vscode/issues/203408
=> fix: skipFiles not matching/negating with special chars

src/targets/node/bootloader.ts, src/test/evaluate/evaluate.ts
=> fix: potential console error when debugging stops

CHANGELOG.md, src/targets/browser/browserAttacher.ts
=> fix: pages not loading in browser after attach browser disconnect

CHANGELOG.md, package-lock.json, src/adapter/breakpoints/conditions/logPoint.ts, src/test/breakpoints/breakpoints-logpoints-basic.txt, src/test/breakpoints/breakpointsTest.ts
=> fix: support object property shorthand in logpoints

CHANGELOG.md, OPTIONS.md, package.nls.json, src/build/generate-contributions.ts, src/configuration.ts, src/ui/configuration/extensionHostConfigurationResolver.ts
Closes https://github.com/microsoft/vscode/issues/199211
=> feat: support running extension test CLI from launch.json

src/build/generate-contributions.ts, src/ui/configuration/extensionHostConfigurationResolver.ts
Refs https://github.com/microsoft/vscode/issues/199211
=> fix: include launch args from test config

CHANGELOG.md, src/common/sourceMaps/renameScopeTree.ts
For https://github.com/microsoft/vscode-js-debug/issues/1948
=> fix: off-by-one error leading to invalid renames

CHANGELOG.md, src/targets/browser/browserPathResolver.ts, src/test/sources/sources-applies-sourcemap-path-mappings-to-sourceurls-vscode204784.txt, src/test/sources/sourcesTest.ts, testWorkspace/web/vscode-204784/index.html
Fixes https://github.com/microsoft/vscode/issues/204784
=> fix: apply sourceMapPathOverrides to sourceURL scripts

package.nls.json
Fixes https://github.com/microsoft/vscode/issues/204671
=> fix: lock commands in strings for localization

CHANGELOG.md, src/adapter/threads.ts
Fixes https://github.com/microsoft/vscode/issues/204581
=> fix: race when stopping on node-internals exceptions

CHANGELOG.md, src/common/sourceMaps/sourceMapResolutionUtils.ts, src/common/urlUtils.ts, src/targets/sourcePathResolver.ts
Do a proper fix for the original Electron issue
Fixes https://github.com/microsoft/vscode/issues/205952
=> fix: resolve sourcemap coming from empty URLs

CHANGELOG.md, src/adapter/objectPreview/contexts.ts, src/adapter/objectPreview/index.ts, src/test/console/console-format-popular-types.txt, src/test/console/console-format-string-format.txt, src/test/console/consoleFormatTest.ts, src/test/evaluate/evaluate.ts, testWorkspace/web/stringFormats.html
Fixes https://github.com/microsoft/vscode/issues/182835
=> fix: inconsistent display of strings with quotes

gulpfile.js
Just skip dependencies instead
=> fix: incorrect useYarn in gulpfile

src/targets/node/nodeLauncherBase.ts
=> fix: ensure space is retained in base environment node_options

src/targets/sourcePathResolver.ts
=> fix: dots in paths causing source map path matching issue

CHANGELOG.md, src/common/pathUtils.ts, src/common/urlUtils.ts, src/targets/node/nodeBinaryProvider.test.ts, src/targets/node/nodeBinaryProvider.ts, src/ui/configuration/extensionHostConfigurationResolver.ts, src/ui/configuration/nodeDebugConfigurationResolver.ts
=> feat: resolve executables from node_modules/.bin automatically

CHANGELOG.md, src/adapter/dwarf/wasmSymbolProvider.ts, src/adapter/threads.ts, src/common/findOpenPortSync.ts
=> fix: debugger hanging on a localhost firewall

src/adapter/templates/getStringyProps.ts, src/test/console/console-format-popular-types.txt, src/test/console/consoleFormatTest.ts
Discussed in https://github.com/mikro-orm/mikro-orm/discussions/5525#discussioncomment-9297903
=> fix: specify inspect depth for node `inspect.custom`

CHANGELOG.md, src/common/findOpenPortSync.ts
Closes https://github.com/microsoft/vscode/issues/214872
=> fix: hanging on certain Linux environments

src/common/urlUtils.ts
=> fix: don't try to debug edge force sign-in page

CHANGELOG.md, src/adapter/sourceContainer.ts
Fixes https://github.com/microsoft/vscode/issues/219031
=> fix: breakpoints at unmapped locations setting in wrong locations

CHANGELOG.md, src/common/processArgs.ts, src/targets/browser/browserArgs.ts, src/test/extension/extensionHostConfigurationProvider.test.ts, src/ui/configuration/extensionHostConfigurationResolver.ts, tsconfig.json
=> fix: automatically guess outFiles in extension development

src/common/logging/fileLogSink.ts, src/ui/processTree/processTree.test.ts, src/ui/processTree/processTree.ts
=> fix: improve matching of inspect argument patterns

CHANGELOG.md, src/adapter/debugAdapter.ts, src/adapter/threads.ts, src/adapter/variableStore.ts, src/dap/api.d.ts, src/dap/errors.ts, src/dap/telemetryClassification.d.ts, src/test/evaluate/evaluate-supports-location-lookup.txt, src/test/evaluate/evaluate.ts
Refs https://github.com/microsoft/debug-adapter-protocol/issues/343
=> feat: adopt location references to link function locations

CHANGELOG.md, src/ui/processTree/processTree.test.ts, src/ui/processTree/processTree.ts
=> fix: process attachment with --inspect=:1234 style

package-lock.json, package.json, src/adapter/dwarf/wasmSymbolProvider.ts, src/adapter/scriptSkipper/implementation.ts, src/adapter/source.ts, src/adapter/sourceContainer.ts, src/build/generate-contributions.ts, src/common/node15Internal.ts, src/configuration.ts, src/targets/node/nodeSourcePathResolver.ts, src/ui/configuration/nodeDebugConfigurationResolver.ts
=> fix: group node internals and WASM to clean up loaded sources view

CHANGELOG.md, src/targets/node/bootloader/filters.ts
Fixes https://github.com/microsoft/vscode/issues/227285
=> fix: running new npm scripts in internal terminal

src/adapter/messageFormat.ts, src/adapter/objectPreview/contexts.ts, src/adapter/objectPreview/index.ts, src/test/console/console-format-ansi-colorization.txt, src/test/console/consoleFormatTest.ts, src/test/logger.ts
Fixes https://github.com/microsoft/vscode/issues/230441
=> fix: support ANSI colorization in logged strings

src/ui/configuration/extensionHostConfigurationResolver.ts
=> fix: ensure default sm resolution paths are kept for transpiled extensions

package-lock.json, package.json, src/adapter/threads.ts
Closes https://github.com/microsoft/vscode/issues/230875
=> fix: wasm breakpoint pausing not working on first run w/ predictor

package-lock.json
=> chore: bump win32-app-container-tokens

src/adapter/threads.ts
=> fix: extraneous threads continued event during shutdown at bp

src/targets/browser/vscodeRendererTargetManager.ts
Closes #2135
Closes https://github.com/microsoft/vscode/issues/232544
=> fix: extension host debug no longer working post-esm

CHANGELOG.md, src/targets/node/terminalNodeLauncher.ts, src/typings/vscode.d.ts
=> fix: use shell integration for more reliable execution for node-temrinal

CHANGELOG.md, src/adapter/debugAdapter.ts, src/build/dapCustom.ts, src/build/generate-contributions.ts, src/dap/api.d.ts, src/ui/prettyPrint.ts
=> fix: allow pretty printing sources when not paused

CHANGELOG.md, gulpfile.js, src/build/generate-contributions.ts, src/ui/basic-wat.configuration.json
Closes https://github.com/microsoft/vscode/issues/224937
=> fix: add a basic language configuration for WAT

src/binder.ts, src/build/wasmCustom.ts, src/cdp/api.d.ts, src/cdp/telemetryClassification.d.ts, src/telemetry/classification.ts
Associated PR https://github.com/dotnet/runtime/pull/111169, updating the event name
=> Update BlazorDebugger telemetry report event

CHANGELOG.md, src/adapter/completions.ts, src/test/completion/completion.test.ts
Fixes https://github.com/microsoft/vscode/issues/243409
=> fix: explicitly specify completion ranges

CHANGELOG.md, src/targets/browser/browserTargetManager.ts, src/targets/browser/browserTargets.ts
Fixes https://github.com/microsoft/vscode/issues/239769
=> fix: race condition when opening attached windows

CHANGELOG.md, src/adapter/templates/serializeForClipboard.ts, src/test/evaluate/evaluate.ts
Fixes https://github.com/microsoft/vscode/issues/241008
=> fix: copy multiline values as template literals

src/common/positions.ts, src/common/sourceMaps/renameScopeAndSourceMap.ts
=> fix: variables in bundled code with source maps aren't renamed properly

src/targets/node/nodeBinaryProvider.ts
Closes https://github.com/microsoft/vscode-js-debug/issues/2218
=> fix: set version manually when using deno

src/extension.ts
Refs https://github.com/microsoft/vscode/issues/254852
=> fix: throw a cancellation error if pickProcess is aborted

src/targets/browser/constructInspectorWSUri.ts
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2538524
=> fix: handle localhost hostname in constructInspectorWSUri function
